#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restAPI_KPP_FOWAG_OSA.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ICT_BAR_PRINTING_KPT")]
	public partial class DB_BAR_PRINTINGDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_T_JOB_PRINTING(TBL_T_JOB_PRINTING instance);
    partial void UpdateTBL_T_JOB_PRINTING(TBL_T_JOB_PRINTING instance);
    partial void DeleteTBL_T_JOB_PRINTING(TBL_T_JOB_PRINTING instance);
    #endregion
		
		public DB_BAR_PRINTINGDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ICT_BAR_PRINTING_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_BAR_PRINTINGDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_BAR_PRINTINGDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_BAR_PRINTINGDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_BAR_PRINTINGDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_T_JOB_PRINTING> TBL_T_JOB_PRINTINGs
		{
			get
			{
				return this.GetTable<TBL_T_JOB_PRINTING>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_JOB_PRINTING")]
	public partial class TBL_T_JOB_PRINTING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _PID;
		
		private string _DSTRCT_CODE;
		
		private string _PRINTER_NAME;
		
		private string _CODE_ID;
		
		private System.Nullable<int> _JOB_TYPE;
		
		private System.Nullable<int> _STATUS;
		
		private string _RESULT;
		
		private System.Nullable<System.DateTime> _LOADING_TIME;
		
		private System.Nullable<System.DateTime> _REQUEST_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPIDChanging(System.Guid value);
    partial void OnPIDChanged();
    partial void OnDSTRCT_CODEChanging(string value);
    partial void OnDSTRCT_CODEChanged();
    partial void OnPRINTER_NAMEChanging(string value);
    partial void OnPRINTER_NAMEChanged();
    partial void OnCODE_IDChanging(string value);
    partial void OnCODE_IDChanged();
    partial void OnJOB_TYPEChanging(System.Nullable<int> value);
    partial void OnJOB_TYPEChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    partial void OnRESULTChanging(string value);
    partial void OnRESULTChanged();
    partial void OnLOADING_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnLOADING_TIMEChanged();
    partial void OnREQUEST_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnREQUEST_TIMEChanged();
    #endregion
		
		public TBL_T_JOB_PRINTING()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(4)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this.OnDSTRCT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DSTRCT_CODE = value;
					this.SendPropertyChanged("DSTRCT_CODE");
					this.OnDSTRCT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINTER_NAME", DbType="VarChar(100)")]
		public string PRINTER_NAME
		{
			get
			{
				return this._PRINTER_NAME;
			}
			set
			{
				if ((this._PRINTER_NAME != value))
				{
					this.OnPRINTER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PRINTER_NAME = value;
					this.SendPropertyChanged("PRINTER_NAME");
					this.OnPRINTER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE_ID", DbType="VarChar(30)")]
		public string CODE_ID
		{
			get
			{
				return this._CODE_ID;
			}
			set
			{
				if ((this._CODE_ID != value))
				{
					this.OnCODE_IDChanging(value);
					this.SendPropertyChanging();
					this._CODE_ID = value;
					this.SendPropertyChanged("CODE_ID");
					this.OnCODE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_TYPE", DbType="Int")]
		public System.Nullable<int> JOB_TYPE
		{
			get
			{
				return this._JOB_TYPE;
			}
			set
			{
				if ((this._JOB_TYPE != value))
				{
					this.OnJOB_TYPEChanging(value);
					this.SendPropertyChanging();
					this._JOB_TYPE = value;
					this.SendPropertyChanged("JOB_TYPE");
					this.OnJOB_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESULT", DbType="VarChar(1000)")]
		public string RESULT
		{
			get
			{
				return this._RESULT;
			}
			set
			{
				if ((this._RESULT != value))
				{
					this.OnRESULTChanging(value);
					this.SendPropertyChanging();
					this._RESULT = value;
					this.SendPropertyChanged("RESULT");
					this.OnRESULTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOADING_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> LOADING_TIME
		{
			get
			{
				return this._LOADING_TIME;
			}
			set
			{
				if ((this._LOADING_TIME != value))
				{
					this.OnLOADING_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LOADING_TIME = value;
					this.SendPropertyChanged("LOADING_TIME");
					this.OnLOADING_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUEST_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> REQUEST_TIME
		{
			get
			{
				return this._REQUEST_TIME;
			}
			set
			{
				if ((this._REQUEST_TIME != value))
				{
					this.OnREQUEST_TIMEChanging(value);
					this.SendPropertyChanging();
					this._REQUEST_TIME = value;
					this.SendPropertyChanged("REQUEST_TIME");
					this.OnREQUEST_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
