#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restAPI_KPP_FOWAG_OSA.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_PLANT_BCS_KPT")]
	public partial class DB_PLANT_BCSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_BACKLOG(TBL_BACKLOG instance);
    partial void UpdateTBL_BACKLOG(TBL_BACKLOG instance);
    partial void DeleteTBL_BACKLOG(TBL_BACKLOG instance);
    partial void InsertTBL_PART(TBL_PART instance);
    partial void UpdateTBL_PART(TBL_PART instance);
    partial void DeleteTBL_PART(TBL_PART instance);
    partial void InsertTBL_BACK_PART(TBL_BACK_PART instance);
    partial void UpdateTBL_BACK_PART(TBL_BACK_PART instance);
    partial void DeleteTBL_BACK_PART(TBL_BACK_PART instance);
    partial void InsertTBL_TR1(TBL_TR1 instance);
    partial void UpdateTBL_TR1(TBL_TR1 instance);
    partial void DeleteTBL_TR1(TBL_TR1 instance);
    #endregion
		
		public DB_PLANT_BCSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_PLANT_BCS_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PLANT_BCSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PLANT_BCSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PLANT_BCSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PLANT_BCSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_BACKLOG> TBL_BACKLOGs
		{
			get
			{
				return this.GetTable<TBL_BACKLOG>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PART> TBL_PARTs
		{
			get
			{
				return this.GetTable<TBL_PART>();
			}
		}
		
		public System.Data.Linq.Table<TBL_BACK_PART> TBL_BACK_PARTs
		{
			get
			{
				return this.GetTable<TBL_BACK_PART>();
			}
		}
		
		public System.Data.Linq.Table<TBL_TR1> TBL_TR1s
		{
			get
			{
				return this.GetTable<TBL_TR1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_BACKLOG")]
	public partial class TBL_BACKLOG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NO_BACKLOG;
		
		private string _WO_NUMBER;
		
		private string _WO_DATE;
		
		private string _EQP_NUMBER;
		
		private string _EGI_ID;
		
		private string _BACKLOG_DESC;
		
		private string _COMPONENT_ID;
		
		private System.Nullable<decimal> _HM_NUMBER;
		
		private string _WR_NUMBER;
		
		private System.Nullable<System.DateTime> _WR_DATE;
		
		private System.Nullable<System.DateTime> _PLAN_REP_DATE;
		
		private System.Nullable<System.DateTime> _PLAN_REP_DATE2;
		
		private System.Nullable<decimal> _EST_HOUR;
		
		private string _BACK_STATUS;
		
		private System.Nullable<System.DateTime> _ACT_REP_DATE;
		
		private System.DateTime _BACKLOG_CREATE_DATE;
		
		private string _DISTRICT;
		
		private string _POSISI;
		
		private System.Nullable<System.DateTime> _BACKLOG_ADM_SUBMIT;
		
		private System.Nullable<System.DateTime> _BACKLOG_PLANNER_SUBMIT;
		
		private System.Nullable<System.DateTime> _BACKLOG_LOGISTIC_SUBMIT;
		
		private System.Nullable<System.DateTime> _STATUS_UPDATE_DATE;
		
		private System.Nullable<System.DateTime> _BACKLOG_ADM_CLOSE;
		
		private string _BACKLOG_STS_UPLOAD;
		
		private System.Nullable<System.DateTime> _BACKLOG_UPLOAD_DATE;
		
		private string _BACKLOG_FIRST_ALERT;
		
		private string _ID_ADM;
		
		private string _ID_PLANNER;
		
		private string _ID_LOGISTIC;
		
		private string _ID_VENDOR;
		
		private string _ID_ADM1;
		
		private string _ID_ADM2;
		
		private System.Nullable<decimal> _BACKLOG_COST;
		
		private string _WR_NUMBER_COMPLETE;
		
		private string _GL_NRP;
		
		private string _GL_NAME;
		
		private string _CLOSING_WO;
		
		private System.Nullable<System.DateTime> _CLOSING_DATE;
		
		private string _VENDOR_STATUS;
		
		private System.Nullable<System.DateTime> _PLAN_REP_DATE_OLD;
		
		private string _LOC_UNIT;
		
		private string _AUTO_CLOSING;
		
		private string _ID_SEND_BACK_TO_PLANNER;
		
		private System.Nullable<System.DateTime> _DATE_SEND_BACK_TO_PLANNER;
		
		private string _REASON_SEND_BACK_TO_PLANNER;
		
		private System.Nullable<System.DateTime> _PLAN_FINISH_DATE;
		
		private System.Nullable<System.DateTime> _PLAN_FINISH_DATE2;
		
		private System.Nullable<int> _MAN_POWER;
		
		private System.Nullable<int> _WELDER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNO_BACKLOGChanging(string value);
    partial void OnNO_BACKLOGChanged();
    partial void OnWO_NUMBERChanging(string value);
    partial void OnWO_NUMBERChanged();
    partial void OnWO_DATEChanging(string value);
    partial void OnWO_DATEChanged();
    partial void OnEQP_NUMBERChanging(string value);
    partial void OnEQP_NUMBERChanged();
    partial void OnEGI_IDChanging(string value);
    partial void OnEGI_IDChanged();
    partial void OnBACKLOG_DESCChanging(string value);
    partial void OnBACKLOG_DESCChanged();
    partial void OnCOMPONENT_IDChanging(string value);
    partial void OnCOMPONENT_IDChanged();
    partial void OnHM_NUMBERChanging(System.Nullable<decimal> value);
    partial void OnHM_NUMBERChanged();
    partial void OnWR_NUMBERChanging(string value);
    partial void OnWR_NUMBERChanged();
    partial void OnWR_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnWR_DATEChanged();
    partial void OnPLAN_REP_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPLAN_REP_DATEChanged();
    partial void OnPLAN_REP_DATE2Changing(System.Nullable<System.DateTime> value);
    partial void OnPLAN_REP_DATE2Changed();
    partial void OnEST_HOURChanging(System.Nullable<decimal> value);
    partial void OnEST_HOURChanged();
    partial void OnBACK_STATUSChanging(string value);
    partial void OnBACK_STATUSChanged();
    partial void OnACT_REP_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnACT_REP_DATEChanged();
    partial void OnBACKLOG_CREATE_DATEChanging(System.DateTime value);
    partial void OnBACKLOG_CREATE_DATEChanged();
    partial void OnDISTRICTChanging(string value);
    partial void OnDISTRICTChanged();
    partial void OnPOSISIChanging(string value);
    partial void OnPOSISIChanged();
    partial void OnBACKLOG_ADM_SUBMITChanging(System.Nullable<System.DateTime> value);
    partial void OnBACKLOG_ADM_SUBMITChanged();
    partial void OnBACKLOG_PLANNER_SUBMITChanging(System.Nullable<System.DateTime> value);
    partial void OnBACKLOG_PLANNER_SUBMITChanged();
    partial void OnBACKLOG_LOGISTIC_SUBMITChanging(System.Nullable<System.DateTime> value);
    partial void OnBACKLOG_LOGISTIC_SUBMITChanged();
    partial void OnSTATUS_UPDATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTATUS_UPDATE_DATEChanged();
    partial void OnBACKLOG_ADM_CLOSEChanging(System.Nullable<System.DateTime> value);
    partial void OnBACKLOG_ADM_CLOSEChanged();
    partial void OnBACKLOG_STS_UPLOADChanging(string value);
    partial void OnBACKLOG_STS_UPLOADChanged();
    partial void OnBACKLOG_UPLOAD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBACKLOG_UPLOAD_DATEChanged();
    partial void OnBACKLOG_FIRST_ALERTChanging(string value);
    partial void OnBACKLOG_FIRST_ALERTChanged();
    partial void OnID_ADMChanging(string value);
    partial void OnID_ADMChanged();
    partial void OnID_PLANNERChanging(string value);
    partial void OnID_PLANNERChanged();
    partial void OnID_LOGISTICChanging(string value);
    partial void OnID_LOGISTICChanged();
    partial void OnID_VENDORChanging(string value);
    partial void OnID_VENDORChanged();
    partial void OnID_ADM1Changing(string value);
    partial void OnID_ADM1Changed();
    partial void OnID_ADM2Changing(string value);
    partial void OnID_ADM2Changed();
    partial void OnBACKLOG_COSTChanging(System.Nullable<decimal> value);
    partial void OnBACKLOG_COSTChanged();
    partial void OnWR_NUMBER_COMPLETEChanging(string value);
    partial void OnWR_NUMBER_COMPLETEChanged();
    partial void OnGL_NRPChanging(string value);
    partial void OnGL_NRPChanged();
    partial void OnGL_NAMEChanging(string value);
    partial void OnGL_NAMEChanged();
    partial void OnCLOSING_WOChanging(string value);
    partial void OnCLOSING_WOChanged();
    partial void OnCLOSING_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCLOSING_DATEChanged();
    partial void OnVENDOR_STATUSChanging(string value);
    partial void OnVENDOR_STATUSChanged();
    partial void OnPLAN_REP_DATE_OLDChanging(System.Nullable<System.DateTime> value);
    partial void OnPLAN_REP_DATE_OLDChanged();
    partial void OnLOC_UNITChanging(string value);
    partial void OnLOC_UNITChanged();
    partial void OnAUTO_CLOSINGChanging(string value);
    partial void OnAUTO_CLOSINGChanged();
    partial void OnID_SEND_BACK_TO_PLANNERChanging(string value);
    partial void OnID_SEND_BACK_TO_PLANNERChanged();
    partial void OnDATE_SEND_BACK_TO_PLANNERChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_SEND_BACK_TO_PLANNERChanged();
    partial void OnREASON_SEND_BACK_TO_PLANNERChanging(string value);
    partial void OnREASON_SEND_BACK_TO_PLANNERChanged();
    partial void OnPLAN_FINISH_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPLAN_FINISH_DATEChanged();
    partial void OnPLAN_FINISH_DATE2Changing(System.Nullable<System.DateTime> value);
    partial void OnPLAN_FINISH_DATE2Changed();
    partial void OnMAN_POWERChanging(System.Nullable<int> value);
    partial void OnMAN_POWERChanged();
    partial void OnWELDERChanging(System.Nullable<int> value);
    partial void OnWELDERChanged();
    #endregion
		
		public TBL_BACKLOG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_BACKLOG", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NO_BACKLOG
		{
			get
			{
				return this._NO_BACKLOG;
			}
			set
			{
				if ((this._NO_BACKLOG != value))
				{
					this.OnNO_BACKLOGChanging(value);
					this.SendPropertyChanging();
					this._NO_BACKLOG = value;
					this.SendPropertyChanged("NO_BACKLOG");
					this.OnNO_BACKLOGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_NUMBER", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string WO_NUMBER
		{
			get
			{
				return this._WO_NUMBER;
			}
			set
			{
				if ((this._WO_NUMBER != value))
				{
					this.OnWO_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._WO_NUMBER = value;
					this.SendPropertyChanged("WO_NUMBER");
					this.OnWO_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_DATE", DbType="VarChar(50)")]
		public string WO_DATE
		{
			get
			{
				return this._WO_DATE;
			}
			set
			{
				if ((this._WO_DATE != value))
				{
					this.OnWO_DATEChanging(value);
					this.SendPropertyChanging();
					this._WO_DATE = value;
					this.SendPropertyChanged("WO_DATE");
					this.OnWO_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQP_NUMBER", DbType="VarChar(40)")]
		public string EQP_NUMBER
		{
			get
			{
				return this._EQP_NUMBER;
			}
			set
			{
				if ((this._EQP_NUMBER != value))
				{
					this.OnEQP_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._EQP_NUMBER = value;
					this.SendPropertyChanged("EQP_NUMBER");
					this.OnEQP_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EGI_ID", DbType="VarChar(40)")]
		public string EGI_ID
		{
			get
			{
				return this._EGI_ID;
			}
			set
			{
				if ((this._EGI_ID != value))
				{
					this.OnEGI_IDChanging(value);
					this.SendPropertyChanging();
					this._EGI_ID = value;
					this.SendPropertyChanged("EGI_ID");
					this.OnEGI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACKLOG_DESC", DbType="VarChar(80)")]
		public string BACKLOG_DESC
		{
			get
			{
				return this._BACKLOG_DESC;
			}
			set
			{
				if ((this._BACKLOG_DESC != value))
				{
					this.OnBACKLOG_DESCChanging(value);
					this.SendPropertyChanging();
					this._BACKLOG_DESC = value;
					this.SendPropertyChanged("BACKLOG_DESC");
					this.OnBACKLOG_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPONENT_ID", DbType="VarChar(20)")]
		public string COMPONENT_ID
		{
			get
			{
				return this._COMPONENT_ID;
			}
			set
			{
				if ((this._COMPONENT_ID != value))
				{
					this.OnCOMPONENT_IDChanging(value);
					this.SendPropertyChanging();
					this._COMPONENT_ID = value;
					this.SendPropertyChanged("COMPONENT_ID");
					this.OnCOMPONENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HM_NUMBER", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> HM_NUMBER
		{
			get
			{
				return this._HM_NUMBER;
			}
			set
			{
				if ((this._HM_NUMBER != value))
				{
					this.OnHM_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._HM_NUMBER = value;
					this.SendPropertyChanged("HM_NUMBER");
					this.OnHM_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WR_NUMBER", DbType="VarChar(500)")]
		public string WR_NUMBER
		{
			get
			{
				return this._WR_NUMBER;
			}
			set
			{
				if ((this._WR_NUMBER != value))
				{
					this.OnWR_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._WR_NUMBER = value;
					this.SendPropertyChanged("WR_NUMBER");
					this.OnWR_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WR_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> WR_DATE
		{
			get
			{
				return this._WR_DATE;
			}
			set
			{
				if ((this._WR_DATE != value))
				{
					this.OnWR_DATEChanging(value);
					this.SendPropertyChanging();
					this._WR_DATE = value;
					this.SendPropertyChanged("WR_DATE");
					this.OnWR_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_REP_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PLAN_REP_DATE
		{
			get
			{
				return this._PLAN_REP_DATE;
			}
			set
			{
				if ((this._PLAN_REP_DATE != value))
				{
					this.OnPLAN_REP_DATEChanging(value);
					this.SendPropertyChanging();
					this._PLAN_REP_DATE = value;
					this.SendPropertyChanged("PLAN_REP_DATE");
					this.OnPLAN_REP_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_REP_DATE2", DbType="DateTime")]
		public System.Nullable<System.DateTime> PLAN_REP_DATE2
		{
			get
			{
				return this._PLAN_REP_DATE2;
			}
			set
			{
				if ((this._PLAN_REP_DATE2 != value))
				{
					this.OnPLAN_REP_DATE2Changing(value);
					this.SendPropertyChanging();
					this._PLAN_REP_DATE2 = value;
					this.SendPropertyChanged("PLAN_REP_DATE2");
					this.OnPLAN_REP_DATE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_HOUR", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> EST_HOUR
		{
			get
			{
				return this._EST_HOUR;
			}
			set
			{
				if ((this._EST_HOUR != value))
				{
					this.OnEST_HOURChanging(value);
					this.SendPropertyChanging();
					this._EST_HOUR = value;
					this.SendPropertyChanged("EST_HOUR");
					this.OnEST_HOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACK_STATUS", DbType="VarChar(20)")]
		public string BACK_STATUS
		{
			get
			{
				return this._BACK_STATUS;
			}
			set
			{
				if ((this._BACK_STATUS != value))
				{
					this.OnBACK_STATUSChanging(value);
					this.SendPropertyChanging();
					this._BACK_STATUS = value;
					this.SendPropertyChanged("BACK_STATUS");
					this.OnBACK_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACT_REP_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ACT_REP_DATE
		{
			get
			{
				return this._ACT_REP_DATE;
			}
			set
			{
				if ((this._ACT_REP_DATE != value))
				{
					this.OnACT_REP_DATEChanging(value);
					this.SendPropertyChanging();
					this._ACT_REP_DATE = value;
					this.SendPropertyChanged("ACT_REP_DATE");
					this.OnACT_REP_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACKLOG_CREATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime BACKLOG_CREATE_DATE
		{
			get
			{
				return this._BACKLOG_CREATE_DATE;
			}
			set
			{
				if ((this._BACKLOG_CREATE_DATE != value))
				{
					this.OnBACKLOG_CREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._BACKLOG_CREATE_DATE = value;
					this.SendPropertyChanged("BACKLOG_CREATE_DATE");
					this.OnBACKLOG_CREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(20)")]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this.OnDISTRICTChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT = value;
					this.SendPropertyChanged("DISTRICT");
					this.OnDISTRICTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSISI", DbType="VarChar(50)")]
		public string POSISI
		{
			get
			{
				return this._POSISI;
			}
			set
			{
				if ((this._POSISI != value))
				{
					this.OnPOSISIChanging(value);
					this.SendPropertyChanging();
					this._POSISI = value;
					this.SendPropertyChanged("POSISI");
					this.OnPOSISIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACKLOG_ADM_SUBMIT", DbType="DateTime")]
		public System.Nullable<System.DateTime> BACKLOG_ADM_SUBMIT
		{
			get
			{
				return this._BACKLOG_ADM_SUBMIT;
			}
			set
			{
				if ((this._BACKLOG_ADM_SUBMIT != value))
				{
					this.OnBACKLOG_ADM_SUBMITChanging(value);
					this.SendPropertyChanging();
					this._BACKLOG_ADM_SUBMIT = value;
					this.SendPropertyChanged("BACKLOG_ADM_SUBMIT");
					this.OnBACKLOG_ADM_SUBMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACKLOG_PLANNER_SUBMIT", DbType="DateTime")]
		public System.Nullable<System.DateTime> BACKLOG_PLANNER_SUBMIT
		{
			get
			{
				return this._BACKLOG_PLANNER_SUBMIT;
			}
			set
			{
				if ((this._BACKLOG_PLANNER_SUBMIT != value))
				{
					this.OnBACKLOG_PLANNER_SUBMITChanging(value);
					this.SendPropertyChanging();
					this._BACKLOG_PLANNER_SUBMIT = value;
					this.SendPropertyChanged("BACKLOG_PLANNER_SUBMIT");
					this.OnBACKLOG_PLANNER_SUBMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACKLOG_LOGISTIC_SUBMIT", DbType="DateTime")]
		public System.Nullable<System.DateTime> BACKLOG_LOGISTIC_SUBMIT
		{
			get
			{
				return this._BACKLOG_LOGISTIC_SUBMIT;
			}
			set
			{
				if ((this._BACKLOG_LOGISTIC_SUBMIT != value))
				{
					this.OnBACKLOG_LOGISTIC_SUBMITChanging(value);
					this.SendPropertyChanging();
					this._BACKLOG_LOGISTIC_SUBMIT = value;
					this.SendPropertyChanged("BACKLOG_LOGISTIC_SUBMIT");
					this.OnBACKLOG_LOGISTIC_SUBMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_UPDATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> STATUS_UPDATE_DATE
		{
			get
			{
				return this._STATUS_UPDATE_DATE;
			}
			set
			{
				if ((this._STATUS_UPDATE_DATE != value))
				{
					this.OnSTATUS_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._STATUS_UPDATE_DATE = value;
					this.SendPropertyChanged("STATUS_UPDATE_DATE");
					this.OnSTATUS_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACKLOG_ADM_CLOSE", DbType="DateTime")]
		public System.Nullable<System.DateTime> BACKLOG_ADM_CLOSE
		{
			get
			{
				return this._BACKLOG_ADM_CLOSE;
			}
			set
			{
				if ((this._BACKLOG_ADM_CLOSE != value))
				{
					this.OnBACKLOG_ADM_CLOSEChanging(value);
					this.SendPropertyChanging();
					this._BACKLOG_ADM_CLOSE = value;
					this.SendPropertyChanged("BACKLOG_ADM_CLOSE");
					this.OnBACKLOG_ADM_CLOSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACKLOG_STS_UPLOAD", DbType="VarChar(50)")]
		public string BACKLOG_STS_UPLOAD
		{
			get
			{
				return this._BACKLOG_STS_UPLOAD;
			}
			set
			{
				if ((this._BACKLOG_STS_UPLOAD != value))
				{
					this.OnBACKLOG_STS_UPLOADChanging(value);
					this.SendPropertyChanging();
					this._BACKLOG_STS_UPLOAD = value;
					this.SendPropertyChanged("BACKLOG_STS_UPLOAD");
					this.OnBACKLOG_STS_UPLOADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACKLOG_UPLOAD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> BACKLOG_UPLOAD_DATE
		{
			get
			{
				return this._BACKLOG_UPLOAD_DATE;
			}
			set
			{
				if ((this._BACKLOG_UPLOAD_DATE != value))
				{
					this.OnBACKLOG_UPLOAD_DATEChanging(value);
					this.SendPropertyChanging();
					this._BACKLOG_UPLOAD_DATE = value;
					this.SendPropertyChanged("BACKLOG_UPLOAD_DATE");
					this.OnBACKLOG_UPLOAD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACKLOG_FIRST_ALERT", DbType="VarChar(40)")]
		public string BACKLOG_FIRST_ALERT
		{
			get
			{
				return this._BACKLOG_FIRST_ALERT;
			}
			set
			{
				if ((this._BACKLOG_FIRST_ALERT != value))
				{
					this.OnBACKLOG_FIRST_ALERTChanging(value);
					this.SendPropertyChanging();
					this._BACKLOG_FIRST_ALERT = value;
					this.SendPropertyChanged("BACKLOG_FIRST_ALERT");
					this.OnBACKLOG_FIRST_ALERTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ADM", DbType="VarChar(50)")]
		public string ID_ADM
		{
			get
			{
				return this._ID_ADM;
			}
			set
			{
				if ((this._ID_ADM != value))
				{
					this.OnID_ADMChanging(value);
					this.SendPropertyChanging();
					this._ID_ADM = value;
					this.SendPropertyChanged("ID_ADM");
					this.OnID_ADMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PLANNER", DbType="VarChar(50)")]
		public string ID_PLANNER
		{
			get
			{
				return this._ID_PLANNER;
			}
			set
			{
				if ((this._ID_PLANNER != value))
				{
					this.OnID_PLANNERChanging(value);
					this.SendPropertyChanging();
					this._ID_PLANNER = value;
					this.SendPropertyChanged("ID_PLANNER");
					this.OnID_PLANNERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOGISTIC", DbType="VarChar(50)")]
		public string ID_LOGISTIC
		{
			get
			{
				return this._ID_LOGISTIC;
			}
			set
			{
				if ((this._ID_LOGISTIC != value))
				{
					this.OnID_LOGISTICChanging(value);
					this.SendPropertyChanging();
					this._ID_LOGISTIC = value;
					this.SendPropertyChanged("ID_LOGISTIC");
					this.OnID_LOGISTICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VENDOR", DbType="VarChar(50)")]
		public string ID_VENDOR
		{
			get
			{
				return this._ID_VENDOR;
			}
			set
			{
				if ((this._ID_VENDOR != value))
				{
					this.OnID_VENDORChanging(value);
					this.SendPropertyChanging();
					this._ID_VENDOR = value;
					this.SendPropertyChanged("ID_VENDOR");
					this.OnID_VENDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ADM1", DbType="VarChar(50)")]
		public string ID_ADM1
		{
			get
			{
				return this._ID_ADM1;
			}
			set
			{
				if ((this._ID_ADM1 != value))
				{
					this.OnID_ADM1Changing(value);
					this.SendPropertyChanging();
					this._ID_ADM1 = value;
					this.SendPropertyChanged("ID_ADM1");
					this.OnID_ADM1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ADM2", DbType="VarChar(50)")]
		public string ID_ADM2
		{
			get
			{
				return this._ID_ADM2;
			}
			set
			{
				if ((this._ID_ADM2 != value))
				{
					this.OnID_ADM2Changing(value);
					this.SendPropertyChanging();
					this._ID_ADM2 = value;
					this.SendPropertyChanged("ID_ADM2");
					this.OnID_ADM2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACKLOG_COST", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> BACKLOG_COST
		{
			get
			{
				return this._BACKLOG_COST;
			}
			set
			{
				if ((this._BACKLOG_COST != value))
				{
					this.OnBACKLOG_COSTChanging(value);
					this.SendPropertyChanging();
					this._BACKLOG_COST = value;
					this.SendPropertyChanged("BACKLOG_COST");
					this.OnBACKLOG_COSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WR_NUMBER_COMPLETE", DbType="VarChar(200)")]
		public string WR_NUMBER_COMPLETE
		{
			get
			{
				return this._WR_NUMBER_COMPLETE;
			}
			set
			{
				if ((this._WR_NUMBER_COMPLETE != value))
				{
					this.OnWR_NUMBER_COMPLETEChanging(value);
					this.SendPropertyChanging();
					this._WR_NUMBER_COMPLETE = value;
					this.SendPropertyChanged("WR_NUMBER_COMPLETE");
					this.OnWR_NUMBER_COMPLETEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GL_NRP", DbType="VarChar(10)")]
		public string GL_NRP
		{
			get
			{
				return this._GL_NRP;
			}
			set
			{
				if ((this._GL_NRP != value))
				{
					this.OnGL_NRPChanging(value);
					this.SendPropertyChanging();
					this._GL_NRP = value;
					this.SendPropertyChanged("GL_NRP");
					this.OnGL_NRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GL_NAME", DbType="VarChar(50)")]
		public string GL_NAME
		{
			get
			{
				return this._GL_NAME;
			}
			set
			{
				if ((this._GL_NAME != value))
				{
					this.OnGL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._GL_NAME = value;
					this.SendPropertyChanged("GL_NAME");
					this.OnGL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSING_WO", DbType="VarChar(50)")]
		public string CLOSING_WO
		{
			get
			{
				return this._CLOSING_WO;
			}
			set
			{
				if ((this._CLOSING_WO != value))
				{
					this.OnCLOSING_WOChanging(value);
					this.SendPropertyChanging();
					this._CLOSING_WO = value;
					this.SendPropertyChanged("CLOSING_WO");
					this.OnCLOSING_WOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSING_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CLOSING_DATE
		{
			get
			{
				return this._CLOSING_DATE;
			}
			set
			{
				if ((this._CLOSING_DATE != value))
				{
					this.OnCLOSING_DATEChanging(value);
					this.SendPropertyChanging();
					this._CLOSING_DATE = value;
					this.SendPropertyChanged("CLOSING_DATE");
					this.OnCLOSING_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR_STATUS", DbType="VarChar(50)")]
		public string VENDOR_STATUS
		{
			get
			{
				return this._VENDOR_STATUS;
			}
			set
			{
				if ((this._VENDOR_STATUS != value))
				{
					this.OnVENDOR_STATUSChanging(value);
					this.SendPropertyChanging();
					this._VENDOR_STATUS = value;
					this.SendPropertyChanged("VENDOR_STATUS");
					this.OnVENDOR_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_REP_DATE_OLD", DbType="DateTime")]
		public System.Nullable<System.DateTime> PLAN_REP_DATE_OLD
		{
			get
			{
				return this._PLAN_REP_DATE_OLD;
			}
			set
			{
				if ((this._PLAN_REP_DATE_OLD != value))
				{
					this.OnPLAN_REP_DATE_OLDChanging(value);
					this.SendPropertyChanging();
					this._PLAN_REP_DATE_OLD = value;
					this.SendPropertyChanged("PLAN_REP_DATE_OLD");
					this.OnPLAN_REP_DATE_OLDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOC_UNIT", DbType="NVarChar(50)")]
		public string LOC_UNIT
		{
			get
			{
				return this._LOC_UNIT;
			}
			set
			{
				if ((this._LOC_UNIT != value))
				{
					this.OnLOC_UNITChanging(value);
					this.SendPropertyChanging();
					this._LOC_UNIT = value;
					this.SendPropertyChanged("LOC_UNIT");
					this.OnLOC_UNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTO_CLOSING", DbType="VarChar(1)")]
		public string AUTO_CLOSING
		{
			get
			{
				return this._AUTO_CLOSING;
			}
			set
			{
				if ((this._AUTO_CLOSING != value))
				{
					this.OnAUTO_CLOSINGChanging(value);
					this.SendPropertyChanging();
					this._AUTO_CLOSING = value;
					this.SendPropertyChanged("AUTO_CLOSING");
					this.OnAUTO_CLOSINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SEND_BACK_TO_PLANNER", DbType="VarChar(50)")]
		public string ID_SEND_BACK_TO_PLANNER
		{
			get
			{
				return this._ID_SEND_BACK_TO_PLANNER;
			}
			set
			{
				if ((this._ID_SEND_BACK_TO_PLANNER != value))
				{
					this.OnID_SEND_BACK_TO_PLANNERChanging(value);
					this.SendPropertyChanging();
					this._ID_SEND_BACK_TO_PLANNER = value;
					this.SendPropertyChanged("ID_SEND_BACK_TO_PLANNER");
					this.OnID_SEND_BACK_TO_PLANNERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SEND_BACK_TO_PLANNER", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_SEND_BACK_TO_PLANNER
		{
			get
			{
				return this._DATE_SEND_BACK_TO_PLANNER;
			}
			set
			{
				if ((this._DATE_SEND_BACK_TO_PLANNER != value))
				{
					this.OnDATE_SEND_BACK_TO_PLANNERChanging(value);
					this.SendPropertyChanging();
					this._DATE_SEND_BACK_TO_PLANNER = value;
					this.SendPropertyChanged("DATE_SEND_BACK_TO_PLANNER");
					this.OnDATE_SEND_BACK_TO_PLANNERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REASON_SEND_BACK_TO_PLANNER", DbType="VarChar(100)")]
		public string REASON_SEND_BACK_TO_PLANNER
		{
			get
			{
				return this._REASON_SEND_BACK_TO_PLANNER;
			}
			set
			{
				if ((this._REASON_SEND_BACK_TO_PLANNER != value))
				{
					this.OnREASON_SEND_BACK_TO_PLANNERChanging(value);
					this.SendPropertyChanging();
					this._REASON_SEND_BACK_TO_PLANNER = value;
					this.SendPropertyChanged("REASON_SEND_BACK_TO_PLANNER");
					this.OnREASON_SEND_BACK_TO_PLANNERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_FINISH_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PLAN_FINISH_DATE
		{
			get
			{
				return this._PLAN_FINISH_DATE;
			}
			set
			{
				if ((this._PLAN_FINISH_DATE != value))
				{
					this.OnPLAN_FINISH_DATEChanging(value);
					this.SendPropertyChanging();
					this._PLAN_FINISH_DATE = value;
					this.SendPropertyChanged("PLAN_FINISH_DATE");
					this.OnPLAN_FINISH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_FINISH_DATE2", DbType="DateTime")]
		public System.Nullable<System.DateTime> PLAN_FINISH_DATE2
		{
			get
			{
				return this._PLAN_FINISH_DATE2;
			}
			set
			{
				if ((this._PLAN_FINISH_DATE2 != value))
				{
					this.OnPLAN_FINISH_DATE2Changing(value);
					this.SendPropertyChanging();
					this._PLAN_FINISH_DATE2 = value;
					this.SendPropertyChanged("PLAN_FINISH_DATE2");
					this.OnPLAN_FINISH_DATE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAN_POWER", DbType="Int")]
		public System.Nullable<int> MAN_POWER
		{
			get
			{
				return this._MAN_POWER;
			}
			set
			{
				if ((this._MAN_POWER != value))
				{
					this.OnMAN_POWERChanging(value);
					this.SendPropertyChanging();
					this._MAN_POWER = value;
					this.SendPropertyChanged("MAN_POWER");
					this.OnMAN_POWERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WELDER", DbType="Int")]
		public System.Nullable<int> WELDER
		{
			get
			{
				return this._WELDER;
			}
			set
			{
				if ((this._WELDER != value))
				{
					this.OnWELDERChanging(value);
					this.SendPropertyChanging();
					this._WELDER = value;
					this.SendPropertyChanged("WELDER");
					this.OnWELDERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PART")]
	public partial class TBL_PART : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PART_ID;
		
		private string _DIST_CODE;
		
		private string _PART_NUMBER;
		
		private string _STOCK_CODE;
		
		private string _PART_DESC;
		
		private string _PART_NAME;
		
		private string _PART_UOM;
		
		private string _PART_PR;
		
		private string _CLASS_CODE;
		
		private string _PART_PRICE_IDR;
		
		private string _PART_PRICE_USD;
		
		private string _UPLOAD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPART_IDChanging(string value);
    partial void OnPART_IDChanged();
    partial void OnDIST_CODEChanging(string value);
    partial void OnDIST_CODEChanged();
    partial void OnPART_NUMBERChanging(string value);
    partial void OnPART_NUMBERChanged();
    partial void OnSTOCK_CODEChanging(string value);
    partial void OnSTOCK_CODEChanged();
    partial void OnPART_DESCChanging(string value);
    partial void OnPART_DESCChanged();
    partial void OnPART_NAMEChanging(string value);
    partial void OnPART_NAMEChanged();
    partial void OnPART_UOMChanging(string value);
    partial void OnPART_UOMChanged();
    partial void OnPART_PRChanging(string value);
    partial void OnPART_PRChanged();
    partial void OnCLASS_CODEChanging(string value);
    partial void OnCLASS_CODEChanged();
    partial void OnPART_PRICE_IDRChanging(string value);
    partial void OnPART_PRICE_IDRChanged();
    partial void OnPART_PRICE_USDChanging(string value);
    partial void OnPART_PRICE_USDChanged();
    partial void OnUPLOADChanging(string value);
    partial void OnUPLOADChanged();
    #endregion
		
		public TBL_PART()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_ID", DbType="VarChar(80) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PART_ID
		{
			get
			{
				return this._PART_ID;
			}
			set
			{
				if ((this._PART_ID != value))
				{
					this.OnPART_IDChanging(value);
					this.SendPropertyChanging();
					this._PART_ID = value;
					this.SendPropertyChanged("PART_ID");
					this.OnPART_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIST_CODE", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string DIST_CODE
		{
			get
			{
				return this._DIST_CODE;
			}
			set
			{
				if ((this._DIST_CODE != value))
				{
					this.OnDIST_CODEChanging(value);
					this.SendPropertyChanging();
					this._DIST_CODE = value;
					this.SendPropertyChanged("DIST_CODE");
					this.OnDIST_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_NUMBER", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string PART_NUMBER
		{
			get
			{
				return this._PART_NUMBER;
			}
			set
			{
				if ((this._PART_NUMBER != value))
				{
					this.OnPART_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._PART_NUMBER = value;
					this.SendPropertyChanged("PART_NUMBER");
					this.OnPART_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK_CODE", DbType="VarChar(40)")]
		public string STOCK_CODE
		{
			get
			{
				return this._STOCK_CODE;
			}
			set
			{
				if ((this._STOCK_CODE != value))
				{
					this.OnSTOCK_CODEChanging(value);
					this.SendPropertyChanging();
					this._STOCK_CODE = value;
					this.SendPropertyChanged("STOCK_CODE");
					this.OnSTOCK_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_DESC", DbType="VarChar(MAX)")]
		public string PART_DESC
		{
			get
			{
				return this._PART_DESC;
			}
			set
			{
				if ((this._PART_DESC != value))
				{
					this.OnPART_DESCChanging(value);
					this.SendPropertyChanging();
					this._PART_DESC = value;
					this.SendPropertyChanged("PART_DESC");
					this.OnPART_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_NAME", DbType="VarChar(MAX)")]
		public string PART_NAME
		{
			get
			{
				return this._PART_NAME;
			}
			set
			{
				if ((this._PART_NAME != value))
				{
					this.OnPART_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PART_NAME = value;
					this.SendPropertyChanged("PART_NAME");
					this.OnPART_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_UOM", DbType="VarChar(MAX)")]
		public string PART_UOM
		{
			get
			{
				return this._PART_UOM;
			}
			set
			{
				if ((this._PART_UOM != value))
				{
					this.OnPART_UOMChanging(value);
					this.SendPropertyChanging();
					this._PART_UOM = value;
					this.SendPropertyChanged("PART_UOM");
					this.OnPART_UOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_PR", DbType="VarChar(MAX)")]
		public string PART_PR
		{
			get
			{
				return this._PART_PR;
			}
			set
			{
				if ((this._PART_PR != value))
				{
					this.OnPART_PRChanging(value);
					this.SendPropertyChanging();
					this._PART_PR = value;
					this.SendPropertyChanged("PART_PR");
					this.OnPART_PRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_CODE", DbType="VarChar(MAX)")]
		public string CLASS_CODE
		{
			get
			{
				return this._CLASS_CODE;
			}
			set
			{
				if ((this._CLASS_CODE != value))
				{
					this.OnCLASS_CODEChanging(value);
					this.SendPropertyChanging();
					this._CLASS_CODE = value;
					this.SendPropertyChanged("CLASS_CODE");
					this.OnCLASS_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_PRICE_IDR", DbType="VarChar(MAX)")]
		public string PART_PRICE_IDR
		{
			get
			{
				return this._PART_PRICE_IDR;
			}
			set
			{
				if ((this._PART_PRICE_IDR != value))
				{
					this.OnPART_PRICE_IDRChanging(value);
					this.SendPropertyChanging();
					this._PART_PRICE_IDR = value;
					this.SendPropertyChanged("PART_PRICE_IDR");
					this.OnPART_PRICE_IDRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_PRICE_USD", DbType="VarChar(MAX)")]
		public string PART_PRICE_USD
		{
			get
			{
				return this._PART_PRICE_USD;
			}
			set
			{
				if ((this._PART_PRICE_USD != value))
				{
					this.OnPART_PRICE_USDChanging(value);
					this.SendPropertyChanging();
					this._PART_PRICE_USD = value;
					this.SendPropertyChanged("PART_PRICE_USD");
					this.OnPART_PRICE_USDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD", DbType="VarChar(50)")]
		public string UPLOAD
		{
			get
			{
				return this._UPLOAD;
			}
			set
			{
				if ((this._UPLOAD != value))
				{
					this.OnUPLOADChanging(value);
					this.SendPropertyChanging();
					this._UPLOAD = value;
					this.SendPropertyChanged("UPLOAD");
					this.OnUPLOADChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_BACK_PART")]
	public partial class TBL_BACK_PART : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BACK_PART_ID;
		
		private string _PART_NUMBER;
		
		private string _STOCK_CODE;
		
		private string _NO_BACKLOG;
		
		private string _FIG_NUMBER;
		
		private string _INDX_NUMBER;
		
		private System.Nullable<long> _QTY_PART;
		
		private System.Nullable<System.DateTime> _INSPECTION_DATE;
		
		private string _EKS_INSPECTION;
		
		private string _PART_STATUS;
		
		private System.DateTime _RECOM_PART_DATE;
		
		private System.Nullable<long> _AVAILABLE_PAMA;
		
		private string _LOCATION_PAMA;
		
		private System.Nullable<System.DateTime> _ETA_PAMA;
		
		private string _VENDOR_PAMA;
		
		private System.Nullable<long> _AVAILABLE_VENDOR;
		
		private string _LOCATION_VENDOR;
		
		private string _DOC_REF_VEN;
		
		private System.Nullable<System.DateTime> _ETA_VENDOR;
		
		private System.Nullable<System.DateTime> _ETA_VENDOR2;
		
		private System.Nullable<System.DateTime> _LAST_ACQ_DATE;
		
		private System.Nullable<long> _QTY_ISSUED;
		
		private string _UPLOAD_STATUS;
		
		private string _PART_CATATAN_VENDOR;
		
		private string _WR_NUMBER;
		
		private string _STOCK_CLASS;
		
		private string _ELL_USER_ID;
		
		private string _ELL_PASSWORD;
		
		private string _ELL_POSISI;
		
		private string _ELL_DIST_CODE;
		
		private string _WH_ID;
		
		private string _DELIV_INSTR;
		
		private string _UPLOAD_REMARKS;
		
		private System.Nullable<System.DateTime> _UPLOAD_TIME;
		
		private string _ID_PO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBACK_PART_IDChanging(string value);
    partial void OnBACK_PART_IDChanged();
    partial void OnPART_NUMBERChanging(string value);
    partial void OnPART_NUMBERChanged();
    partial void OnSTOCK_CODEChanging(string value);
    partial void OnSTOCK_CODEChanged();
    partial void OnNO_BACKLOGChanging(string value);
    partial void OnNO_BACKLOGChanged();
    partial void OnFIG_NUMBERChanging(string value);
    partial void OnFIG_NUMBERChanged();
    partial void OnINDX_NUMBERChanging(string value);
    partial void OnINDX_NUMBERChanged();
    partial void OnQTY_PARTChanging(System.Nullable<long> value);
    partial void OnQTY_PARTChanged();
    partial void OnINSPECTION_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnINSPECTION_DATEChanged();
    partial void OnEKS_INSPECTIONChanging(string value);
    partial void OnEKS_INSPECTIONChanged();
    partial void OnPART_STATUSChanging(string value);
    partial void OnPART_STATUSChanged();
    partial void OnRECOM_PART_DATEChanging(System.DateTime value);
    partial void OnRECOM_PART_DATEChanged();
    partial void OnAVAILABLE_PAMAChanging(System.Nullable<long> value);
    partial void OnAVAILABLE_PAMAChanged();
    partial void OnLOCATION_PAMAChanging(string value);
    partial void OnLOCATION_PAMAChanged();
    partial void OnETA_PAMAChanging(System.Nullable<System.DateTime> value);
    partial void OnETA_PAMAChanged();
    partial void OnVENDOR_PAMAChanging(string value);
    partial void OnVENDOR_PAMAChanged();
    partial void OnAVAILABLE_VENDORChanging(System.Nullable<long> value);
    partial void OnAVAILABLE_VENDORChanged();
    partial void OnLOCATION_VENDORChanging(string value);
    partial void OnLOCATION_VENDORChanged();
    partial void OnDOC_REF_VENChanging(string value);
    partial void OnDOC_REF_VENChanged();
    partial void OnETA_VENDORChanging(System.Nullable<System.DateTime> value);
    partial void OnETA_VENDORChanged();
    partial void OnETA_VENDOR2Changing(System.Nullable<System.DateTime> value);
    partial void OnETA_VENDOR2Changed();
    partial void OnLAST_ACQ_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_ACQ_DATEChanged();
    partial void OnQTY_ISSUEDChanging(System.Nullable<long> value);
    partial void OnQTY_ISSUEDChanged();
    partial void OnUPLOAD_STATUSChanging(string value);
    partial void OnUPLOAD_STATUSChanged();
    partial void OnPART_CATATAN_VENDORChanging(string value);
    partial void OnPART_CATATAN_VENDORChanged();
    partial void OnWR_NUMBERChanging(string value);
    partial void OnWR_NUMBERChanged();
    partial void OnSTOCK_CLASSChanging(string value);
    partial void OnSTOCK_CLASSChanged();
    partial void OnELL_USER_IDChanging(string value);
    partial void OnELL_USER_IDChanged();
    partial void OnELL_PASSWORDChanging(string value);
    partial void OnELL_PASSWORDChanged();
    partial void OnELL_POSISIChanging(string value);
    partial void OnELL_POSISIChanged();
    partial void OnELL_DIST_CODEChanging(string value);
    partial void OnELL_DIST_CODEChanged();
    partial void OnWH_IDChanging(string value);
    partial void OnWH_IDChanged();
    partial void OnDELIV_INSTRChanging(string value);
    partial void OnDELIV_INSTRChanged();
    partial void OnUPLOAD_REMARKSChanging(string value);
    partial void OnUPLOAD_REMARKSChanged();
    partial void OnUPLOAD_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPLOAD_TIMEChanged();
    partial void OnID_POChanging(string value);
    partial void OnID_POChanged();
    #endregion
		
		public TBL_BACK_PART()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BACK_PART_ID", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BACK_PART_ID
		{
			get
			{
				return this._BACK_PART_ID;
			}
			set
			{
				if ((this._BACK_PART_ID != value))
				{
					this.OnBACK_PART_IDChanging(value);
					this.SendPropertyChanging();
					this._BACK_PART_ID = value;
					this.SendPropertyChanged("BACK_PART_ID");
					this.OnBACK_PART_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_NUMBER", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string PART_NUMBER
		{
			get
			{
				return this._PART_NUMBER;
			}
			set
			{
				if ((this._PART_NUMBER != value))
				{
					this.OnPART_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._PART_NUMBER = value;
					this.SendPropertyChanged("PART_NUMBER");
					this.OnPART_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string STOCK_CODE
		{
			get
			{
				return this._STOCK_CODE;
			}
			set
			{
				if ((this._STOCK_CODE != value))
				{
					this.OnSTOCK_CODEChanging(value);
					this.SendPropertyChanging();
					this._STOCK_CODE = value;
					this.SendPropertyChanged("STOCK_CODE");
					this.OnSTOCK_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_BACKLOG", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NO_BACKLOG
		{
			get
			{
				return this._NO_BACKLOG;
			}
			set
			{
				if ((this._NO_BACKLOG != value))
				{
					this.OnNO_BACKLOGChanging(value);
					this.SendPropertyChanging();
					this._NO_BACKLOG = value;
					this.SendPropertyChanged("NO_BACKLOG");
					this.OnNO_BACKLOGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIG_NUMBER", DbType="VarChar(20)")]
		public string FIG_NUMBER
		{
			get
			{
				return this._FIG_NUMBER;
			}
			set
			{
				if ((this._FIG_NUMBER != value))
				{
					this.OnFIG_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._FIG_NUMBER = value;
					this.SendPropertyChanged("FIG_NUMBER");
					this.OnFIG_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDX_NUMBER", DbType="VarChar(20)")]
		public string INDX_NUMBER
		{
			get
			{
				return this._INDX_NUMBER;
			}
			set
			{
				if ((this._INDX_NUMBER != value))
				{
					this.OnINDX_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._INDX_NUMBER = value;
					this.SendPropertyChanged("INDX_NUMBER");
					this.OnINDX_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY_PART", DbType="BigInt")]
		public System.Nullable<long> QTY_PART
		{
			get
			{
				return this._QTY_PART;
			}
			set
			{
				if ((this._QTY_PART != value))
				{
					this.OnQTY_PARTChanging(value);
					this.SendPropertyChanging();
					this._QTY_PART = value;
					this.SendPropertyChanged("QTY_PART");
					this.OnQTY_PARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSPECTION_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> INSPECTION_DATE
		{
			get
			{
				return this._INSPECTION_DATE;
			}
			set
			{
				if ((this._INSPECTION_DATE != value))
				{
					this.OnINSPECTION_DATEChanging(value);
					this.SendPropertyChanging();
					this._INSPECTION_DATE = value;
					this.SendPropertyChanged("INSPECTION_DATE");
					this.OnINSPECTION_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EKS_INSPECTION", DbType="VarChar(30)")]
		public string EKS_INSPECTION
		{
			get
			{
				return this._EKS_INSPECTION;
			}
			set
			{
				if ((this._EKS_INSPECTION != value))
				{
					this.OnEKS_INSPECTIONChanging(value);
					this.SendPropertyChanging();
					this._EKS_INSPECTION = value;
					this.SendPropertyChanged("EKS_INSPECTION");
					this.OnEKS_INSPECTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_STATUS", DbType="VarChar(30)")]
		public string PART_STATUS
		{
			get
			{
				return this._PART_STATUS;
			}
			set
			{
				if ((this._PART_STATUS != value))
				{
					this.OnPART_STATUSChanging(value);
					this.SendPropertyChanging();
					this._PART_STATUS = value;
					this.SendPropertyChanged("PART_STATUS");
					this.OnPART_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECOM_PART_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime RECOM_PART_DATE
		{
			get
			{
				return this._RECOM_PART_DATE;
			}
			set
			{
				if ((this._RECOM_PART_DATE != value))
				{
					this.OnRECOM_PART_DATEChanging(value);
					this.SendPropertyChanging();
					this._RECOM_PART_DATE = value;
					this.SendPropertyChanged("RECOM_PART_DATE");
					this.OnRECOM_PART_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVAILABLE_PAMA", DbType="BigInt")]
		public System.Nullable<long> AVAILABLE_PAMA
		{
			get
			{
				return this._AVAILABLE_PAMA;
			}
			set
			{
				if ((this._AVAILABLE_PAMA != value))
				{
					this.OnAVAILABLE_PAMAChanging(value);
					this.SendPropertyChanging();
					this._AVAILABLE_PAMA = value;
					this.SendPropertyChanged("AVAILABLE_PAMA");
					this.OnAVAILABLE_PAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_PAMA", DbType="VarChar(40)")]
		public string LOCATION_PAMA
		{
			get
			{
				return this._LOCATION_PAMA;
			}
			set
			{
				if ((this._LOCATION_PAMA != value))
				{
					this.OnLOCATION_PAMAChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_PAMA = value;
					this.SendPropertyChanged("LOCATION_PAMA");
					this.OnLOCATION_PAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETA_PAMA", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETA_PAMA
		{
			get
			{
				return this._ETA_PAMA;
			}
			set
			{
				if ((this._ETA_PAMA != value))
				{
					this.OnETA_PAMAChanging(value);
					this.SendPropertyChanging();
					this._ETA_PAMA = value;
					this.SendPropertyChanged("ETA_PAMA");
					this.OnETA_PAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR_PAMA", DbType="VarChar(30)")]
		public string VENDOR_PAMA
		{
			get
			{
				return this._VENDOR_PAMA;
			}
			set
			{
				if ((this._VENDOR_PAMA != value))
				{
					this.OnVENDOR_PAMAChanging(value);
					this.SendPropertyChanging();
					this._VENDOR_PAMA = value;
					this.SendPropertyChanged("VENDOR_PAMA");
					this.OnVENDOR_PAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVAILABLE_VENDOR", DbType="BigInt")]
		public System.Nullable<long> AVAILABLE_VENDOR
		{
			get
			{
				return this._AVAILABLE_VENDOR;
			}
			set
			{
				if ((this._AVAILABLE_VENDOR != value))
				{
					this.OnAVAILABLE_VENDORChanging(value);
					this.SendPropertyChanging();
					this._AVAILABLE_VENDOR = value;
					this.SendPropertyChanged("AVAILABLE_VENDOR");
					this.OnAVAILABLE_VENDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_VENDOR", DbType="VarChar(40)")]
		public string LOCATION_VENDOR
		{
			get
			{
				return this._LOCATION_VENDOR;
			}
			set
			{
				if ((this._LOCATION_VENDOR != value))
				{
					this.OnLOCATION_VENDORChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_VENDOR = value;
					this.SendPropertyChanged("LOCATION_VENDOR");
					this.OnLOCATION_VENDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_REF_VEN", DbType="VarChar(80)")]
		public string DOC_REF_VEN
		{
			get
			{
				return this._DOC_REF_VEN;
			}
			set
			{
				if ((this._DOC_REF_VEN != value))
				{
					this.OnDOC_REF_VENChanging(value);
					this.SendPropertyChanging();
					this._DOC_REF_VEN = value;
					this.SendPropertyChanged("DOC_REF_VEN");
					this.OnDOC_REF_VENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETA_VENDOR", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETA_VENDOR
		{
			get
			{
				return this._ETA_VENDOR;
			}
			set
			{
				if ((this._ETA_VENDOR != value))
				{
					this.OnETA_VENDORChanging(value);
					this.SendPropertyChanging();
					this._ETA_VENDOR = value;
					this.SendPropertyChanged("ETA_VENDOR");
					this.OnETA_VENDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETA_VENDOR2", DbType="DateTime")]
		public System.Nullable<System.DateTime> ETA_VENDOR2
		{
			get
			{
				return this._ETA_VENDOR2;
			}
			set
			{
				if ((this._ETA_VENDOR2 != value))
				{
					this.OnETA_VENDOR2Changing(value);
					this.SendPropertyChanging();
					this._ETA_VENDOR2 = value;
					this.SendPropertyChanged("ETA_VENDOR2");
					this.OnETA_VENDOR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_ACQ_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAST_ACQ_DATE
		{
			get
			{
				return this._LAST_ACQ_DATE;
			}
			set
			{
				if ((this._LAST_ACQ_DATE != value))
				{
					this.OnLAST_ACQ_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_ACQ_DATE = value;
					this.SendPropertyChanged("LAST_ACQ_DATE");
					this.OnLAST_ACQ_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY_ISSUED", DbType="BigInt")]
		public System.Nullable<long> QTY_ISSUED
		{
			get
			{
				return this._QTY_ISSUED;
			}
			set
			{
				if ((this._QTY_ISSUED != value))
				{
					this.OnQTY_ISSUEDChanging(value);
					this.SendPropertyChanging();
					this._QTY_ISSUED = value;
					this.SendPropertyChanged("QTY_ISSUED");
					this.OnQTY_ISSUEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_STATUS", DbType="VarChar(50)")]
		public string UPLOAD_STATUS
		{
			get
			{
				return this._UPLOAD_STATUS;
			}
			set
			{
				if ((this._UPLOAD_STATUS != value))
				{
					this.OnUPLOAD_STATUSChanging(value);
					this.SendPropertyChanging();
					this._UPLOAD_STATUS = value;
					this.SendPropertyChanged("UPLOAD_STATUS");
					this.OnUPLOAD_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PART_CATATAN_VENDOR", DbType="VarChar(100)")]
		public string PART_CATATAN_VENDOR
		{
			get
			{
				return this._PART_CATATAN_VENDOR;
			}
			set
			{
				if ((this._PART_CATATAN_VENDOR != value))
				{
					this.OnPART_CATATAN_VENDORChanging(value);
					this.SendPropertyChanging();
					this._PART_CATATAN_VENDOR = value;
					this.SendPropertyChanged("PART_CATATAN_VENDOR");
					this.OnPART_CATATAN_VENDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WR_NUMBER", DbType="VarChar(30)")]
		public string WR_NUMBER
		{
			get
			{
				return this._WR_NUMBER;
			}
			set
			{
				if ((this._WR_NUMBER != value))
				{
					this.OnWR_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._WR_NUMBER = value;
					this.SendPropertyChanged("WR_NUMBER");
					this.OnWR_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK_CLASS", DbType="VarChar(50)")]
		public string STOCK_CLASS
		{
			get
			{
				return this._STOCK_CLASS;
			}
			set
			{
				if ((this._STOCK_CLASS != value))
				{
					this.OnSTOCK_CLASSChanging(value);
					this.SendPropertyChanging();
					this._STOCK_CLASS = value;
					this.SendPropertyChanged("STOCK_CLASS");
					this.OnSTOCK_CLASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELL_USER_ID", DbType="VarChar(50)")]
		public string ELL_USER_ID
		{
			get
			{
				return this._ELL_USER_ID;
			}
			set
			{
				if ((this._ELL_USER_ID != value))
				{
					this.OnELL_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._ELL_USER_ID = value;
					this.SendPropertyChanged("ELL_USER_ID");
					this.OnELL_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELL_PASSWORD", DbType="VarChar(50)")]
		public string ELL_PASSWORD
		{
			get
			{
				return this._ELL_PASSWORD;
			}
			set
			{
				if ((this._ELL_PASSWORD != value))
				{
					this.OnELL_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._ELL_PASSWORD = value;
					this.SendPropertyChanged("ELL_PASSWORD");
					this.OnELL_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELL_POSISI", DbType="VarChar(50)")]
		public string ELL_POSISI
		{
			get
			{
				return this._ELL_POSISI;
			}
			set
			{
				if ((this._ELL_POSISI != value))
				{
					this.OnELL_POSISIChanging(value);
					this.SendPropertyChanging();
					this._ELL_POSISI = value;
					this.SendPropertyChanged("ELL_POSISI");
					this.OnELL_POSISIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELL_DIST_CODE", DbType="VarChar(50)")]
		public string ELL_DIST_CODE
		{
			get
			{
				return this._ELL_DIST_CODE;
			}
			set
			{
				if ((this._ELL_DIST_CODE != value))
				{
					this.OnELL_DIST_CODEChanging(value);
					this.SendPropertyChanging();
					this._ELL_DIST_CODE = value;
					this.SendPropertyChanged("ELL_DIST_CODE");
					this.OnELL_DIST_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WH_ID", DbType="VarChar(50)")]
		public string WH_ID
		{
			get
			{
				return this._WH_ID;
			}
			set
			{
				if ((this._WH_ID != value))
				{
					this.OnWH_IDChanging(value);
					this.SendPropertyChanging();
					this._WH_ID = value;
					this.SendPropertyChanged("WH_ID");
					this.OnWH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELIV_INSTR", DbType="VarChar(100)")]
		public string DELIV_INSTR
		{
			get
			{
				return this._DELIV_INSTR;
			}
			set
			{
				if ((this._DELIV_INSTR != value))
				{
					this.OnDELIV_INSTRChanging(value);
					this.SendPropertyChanging();
					this._DELIV_INSTR = value;
					this.SendPropertyChanged("DELIV_INSTR");
					this.OnDELIV_INSTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_REMARKS", DbType="VarChar(255)")]
		public string UPLOAD_REMARKS
		{
			get
			{
				return this._UPLOAD_REMARKS;
			}
			set
			{
				if ((this._UPLOAD_REMARKS != value))
				{
					this.OnUPLOAD_REMARKSChanging(value);
					this.SendPropertyChanging();
					this._UPLOAD_REMARKS = value;
					this.SendPropertyChanged("UPLOAD_REMARKS");
					this.OnUPLOAD_REMARKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPLOAD_TIME
		{
			get
			{
				return this._UPLOAD_TIME;
			}
			set
			{
				if ((this._UPLOAD_TIME != value))
				{
					this.OnUPLOAD_TIMEChanging(value);
					this.SendPropertyChanging();
					this._UPLOAD_TIME = value;
					this.SendPropertyChanged("UPLOAD_TIME");
					this.OnUPLOAD_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PO", DbType="VarChar(255)")]
		public string ID_PO
		{
			get
			{
				return this._ID_PO;
			}
			set
			{
				if ((this._ID_PO != value))
				{
					this.OnID_POChanging(value);
					this.SendPropertyChanging();
					this._ID_PO = value;
					this.SendPropertyChanged("ID_PO");
					this.OnID_POChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_TR1")]
	public partial class TBL_TR1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _TR1_ID;
		
		private string _TR1_USER_ID;
		
		private string _TR1_PASSWORD;
		
		private string _TR1_DIST_CODE;
		
		private string _TR1_WONO;
		
		private string _TR1_POSISI;
		
		private string _TR1_REP_DATE;
		
		private string _TR1_UPLOAD_ELLIPSE;
		
		private string _TR1_DESCRIPTION;
		
		private string _TR1_EQUIPNO;
		
		private string _TR1_NO_BACKLOG;
		
		private string _TR1_WO_DATE;
		
		private string _TR1_COMPONENTID;
		
		private string _TR1_EGI_ID;
		
		private string _TR1_STANDARD_JOB;
		
		private string _TR1_ORIG;
		
		private string _TR1_WORK_GROUP;
		
		private System.Nullable<long> _TR1_JOB_ID;
		
		private string _TR1_REMARKS;
		
		private System.Nullable<System.DateTime> _TR1_UPDATE_TIME;
		
		private string _TR1_INSERT_TIME;
		
		private string _TR1_PLAN_FINISH_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTR1_IDChanging(long value);
    partial void OnTR1_IDChanged();
    partial void OnTR1_USER_IDChanging(string value);
    partial void OnTR1_USER_IDChanged();
    partial void OnTR1_PASSWORDChanging(string value);
    partial void OnTR1_PASSWORDChanged();
    partial void OnTR1_DIST_CODEChanging(string value);
    partial void OnTR1_DIST_CODEChanged();
    partial void OnTR1_WONOChanging(string value);
    partial void OnTR1_WONOChanged();
    partial void OnTR1_POSISIChanging(string value);
    partial void OnTR1_POSISIChanged();
    partial void OnTR1_REP_DATEChanging(string value);
    partial void OnTR1_REP_DATEChanged();
    partial void OnTR1_UPLOAD_ELLIPSEChanging(string value);
    partial void OnTR1_UPLOAD_ELLIPSEChanged();
    partial void OnTR1_DESCRIPTIONChanging(string value);
    partial void OnTR1_DESCRIPTIONChanged();
    partial void OnTR1_EQUIPNOChanging(string value);
    partial void OnTR1_EQUIPNOChanged();
    partial void OnTR1_NO_BACKLOGChanging(string value);
    partial void OnTR1_NO_BACKLOGChanged();
    partial void OnTR1_WO_DATEChanging(string value);
    partial void OnTR1_WO_DATEChanged();
    partial void OnTR1_COMPONENTIDChanging(string value);
    partial void OnTR1_COMPONENTIDChanged();
    partial void OnTR1_EGI_IDChanging(string value);
    partial void OnTR1_EGI_IDChanged();
    partial void OnTR1_STANDARD_JOBChanging(string value);
    partial void OnTR1_STANDARD_JOBChanged();
    partial void OnTR1_ORIGChanging(string value);
    partial void OnTR1_ORIGChanged();
    partial void OnTR1_WORK_GROUPChanging(string value);
    partial void OnTR1_WORK_GROUPChanged();
    partial void OnTR1_JOB_IDChanging(System.Nullable<long> value);
    partial void OnTR1_JOB_IDChanged();
    partial void OnTR1_REMARKSChanging(string value);
    partial void OnTR1_REMARKSChanged();
    partial void OnTR1_UPDATE_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnTR1_UPDATE_TIMEChanged();
    partial void OnTR1_INSERT_TIMEChanging(string value);
    partial void OnTR1_INSERT_TIMEChanged();
    partial void OnTR1_PLAN_FINISH_DATEChanging(string value);
    partial void OnTR1_PLAN_FINISH_DATEChanged();
    #endregion
		
		public TBL_TR1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long TR1_ID
		{
			get
			{
				return this._TR1_ID;
			}
			set
			{
				if ((this._TR1_ID != value))
				{
					this.OnTR1_IDChanging(value);
					this.SendPropertyChanging();
					this._TR1_ID = value;
					this.SendPropertyChanged("TR1_ID");
					this.OnTR1_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_USER_ID", DbType="VarChar(50)")]
		public string TR1_USER_ID
		{
			get
			{
				return this._TR1_USER_ID;
			}
			set
			{
				if ((this._TR1_USER_ID != value))
				{
					this.OnTR1_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._TR1_USER_ID = value;
					this.SendPropertyChanged("TR1_USER_ID");
					this.OnTR1_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_PASSWORD", DbType="VarChar(50)")]
		public string TR1_PASSWORD
		{
			get
			{
				return this._TR1_PASSWORD;
			}
			set
			{
				if ((this._TR1_PASSWORD != value))
				{
					this.OnTR1_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._TR1_PASSWORD = value;
					this.SendPropertyChanged("TR1_PASSWORD");
					this.OnTR1_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_DIST_CODE", DbType="VarChar(50)")]
		public string TR1_DIST_CODE
		{
			get
			{
				return this._TR1_DIST_CODE;
			}
			set
			{
				if ((this._TR1_DIST_CODE != value))
				{
					this.OnTR1_DIST_CODEChanging(value);
					this.SendPropertyChanging();
					this._TR1_DIST_CODE = value;
					this.SendPropertyChanged("TR1_DIST_CODE");
					this.OnTR1_DIST_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_WONO", DbType="VarChar(50)")]
		public string TR1_WONO
		{
			get
			{
				return this._TR1_WONO;
			}
			set
			{
				if ((this._TR1_WONO != value))
				{
					this.OnTR1_WONOChanging(value);
					this.SendPropertyChanging();
					this._TR1_WONO = value;
					this.SendPropertyChanged("TR1_WONO");
					this.OnTR1_WONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_POSISI", DbType="VarChar(50)")]
		public string TR1_POSISI
		{
			get
			{
				return this._TR1_POSISI;
			}
			set
			{
				if ((this._TR1_POSISI != value))
				{
					this.OnTR1_POSISIChanging(value);
					this.SendPropertyChanging();
					this._TR1_POSISI = value;
					this.SendPropertyChanged("TR1_POSISI");
					this.OnTR1_POSISIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_REP_DATE", DbType="VarChar(50)")]
		public string TR1_REP_DATE
		{
			get
			{
				return this._TR1_REP_DATE;
			}
			set
			{
				if ((this._TR1_REP_DATE != value))
				{
					this.OnTR1_REP_DATEChanging(value);
					this.SendPropertyChanging();
					this._TR1_REP_DATE = value;
					this.SendPropertyChanged("TR1_REP_DATE");
					this.OnTR1_REP_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_UPLOAD_ELLIPSE", DbType="VarChar(50)")]
		public string TR1_UPLOAD_ELLIPSE
		{
			get
			{
				return this._TR1_UPLOAD_ELLIPSE;
			}
			set
			{
				if ((this._TR1_UPLOAD_ELLIPSE != value))
				{
					this.OnTR1_UPLOAD_ELLIPSEChanging(value);
					this.SendPropertyChanging();
					this._TR1_UPLOAD_ELLIPSE = value;
					this.SendPropertyChanged("TR1_UPLOAD_ELLIPSE");
					this.OnTR1_UPLOAD_ELLIPSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_DESCRIPTION", DbType="VarChar(50)")]
		public string TR1_DESCRIPTION
		{
			get
			{
				return this._TR1_DESCRIPTION;
			}
			set
			{
				if ((this._TR1_DESCRIPTION != value))
				{
					this.OnTR1_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._TR1_DESCRIPTION = value;
					this.SendPropertyChanged("TR1_DESCRIPTION");
					this.OnTR1_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_EQUIPNO", DbType="VarChar(50)")]
		public string TR1_EQUIPNO
		{
			get
			{
				return this._TR1_EQUIPNO;
			}
			set
			{
				if ((this._TR1_EQUIPNO != value))
				{
					this.OnTR1_EQUIPNOChanging(value);
					this.SendPropertyChanging();
					this._TR1_EQUIPNO = value;
					this.SendPropertyChanged("TR1_EQUIPNO");
					this.OnTR1_EQUIPNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_NO_BACKLOG", DbType="VarChar(30)")]
		public string TR1_NO_BACKLOG
		{
			get
			{
				return this._TR1_NO_BACKLOG;
			}
			set
			{
				if ((this._TR1_NO_BACKLOG != value))
				{
					this.OnTR1_NO_BACKLOGChanging(value);
					this.SendPropertyChanging();
					this._TR1_NO_BACKLOG = value;
					this.SendPropertyChanged("TR1_NO_BACKLOG");
					this.OnTR1_NO_BACKLOGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_WO_DATE", DbType="VarChar(50)")]
		public string TR1_WO_DATE
		{
			get
			{
				return this._TR1_WO_DATE;
			}
			set
			{
				if ((this._TR1_WO_DATE != value))
				{
					this.OnTR1_WO_DATEChanging(value);
					this.SendPropertyChanging();
					this._TR1_WO_DATE = value;
					this.SendPropertyChanged("TR1_WO_DATE");
					this.OnTR1_WO_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_COMPONENTID", DbType="VarChar(50)")]
		public string TR1_COMPONENTID
		{
			get
			{
				return this._TR1_COMPONENTID;
			}
			set
			{
				if ((this._TR1_COMPONENTID != value))
				{
					this.OnTR1_COMPONENTIDChanging(value);
					this.SendPropertyChanging();
					this._TR1_COMPONENTID = value;
					this.SendPropertyChanged("TR1_COMPONENTID");
					this.OnTR1_COMPONENTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_EGI_ID", DbType="VarChar(50)")]
		public string TR1_EGI_ID
		{
			get
			{
				return this._TR1_EGI_ID;
			}
			set
			{
				if ((this._TR1_EGI_ID != value))
				{
					this.OnTR1_EGI_IDChanging(value);
					this.SendPropertyChanging();
					this._TR1_EGI_ID = value;
					this.SendPropertyChanged("TR1_EGI_ID");
					this.OnTR1_EGI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_STANDARD_JOB", DbType="VarChar(50)")]
		public string TR1_STANDARD_JOB
		{
			get
			{
				return this._TR1_STANDARD_JOB;
			}
			set
			{
				if ((this._TR1_STANDARD_JOB != value))
				{
					this.OnTR1_STANDARD_JOBChanging(value);
					this.SendPropertyChanging();
					this._TR1_STANDARD_JOB = value;
					this.SendPropertyChanged("TR1_STANDARD_JOB");
					this.OnTR1_STANDARD_JOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_ORIG", DbType="VarChar(50)")]
		public string TR1_ORIG
		{
			get
			{
				return this._TR1_ORIG;
			}
			set
			{
				if ((this._TR1_ORIG != value))
				{
					this.OnTR1_ORIGChanging(value);
					this.SendPropertyChanging();
					this._TR1_ORIG = value;
					this.SendPropertyChanged("TR1_ORIG");
					this.OnTR1_ORIGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_WORK_GROUP", DbType="VarChar(50)")]
		public string TR1_WORK_GROUP
		{
			get
			{
				return this._TR1_WORK_GROUP;
			}
			set
			{
				if ((this._TR1_WORK_GROUP != value))
				{
					this.OnTR1_WORK_GROUPChanging(value);
					this.SendPropertyChanging();
					this._TR1_WORK_GROUP = value;
					this.SendPropertyChanged("TR1_WORK_GROUP");
					this.OnTR1_WORK_GROUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_JOB_ID", DbType="BigInt")]
		public System.Nullable<long> TR1_JOB_ID
		{
			get
			{
				return this._TR1_JOB_ID;
			}
			set
			{
				if ((this._TR1_JOB_ID != value))
				{
					this.OnTR1_JOB_IDChanging(value);
					this.SendPropertyChanging();
					this._TR1_JOB_ID = value;
					this.SendPropertyChanged("TR1_JOB_ID");
					this.OnTR1_JOB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_REMARKS", DbType="VarChar(255)")]
		public string TR1_REMARKS
		{
			get
			{
				return this._TR1_REMARKS;
			}
			set
			{
				if ((this._TR1_REMARKS != value))
				{
					this.OnTR1_REMARKSChanging(value);
					this.SendPropertyChanging();
					this._TR1_REMARKS = value;
					this.SendPropertyChanged("TR1_REMARKS");
					this.OnTR1_REMARKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_UPDATE_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> TR1_UPDATE_TIME
		{
			get
			{
				return this._TR1_UPDATE_TIME;
			}
			set
			{
				if ((this._TR1_UPDATE_TIME != value))
				{
					this.OnTR1_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._TR1_UPDATE_TIME = value;
					this.SendPropertyChanged("TR1_UPDATE_TIME");
					this.OnTR1_UPDATE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_INSERT_TIME", DbType="VarChar(50)")]
		public string TR1_INSERT_TIME
		{
			get
			{
				return this._TR1_INSERT_TIME;
			}
			set
			{
				if ((this._TR1_INSERT_TIME != value))
				{
					this.OnTR1_INSERT_TIMEChanging(value);
					this.SendPropertyChanging();
					this._TR1_INSERT_TIME = value;
					this.SendPropertyChanged("TR1_INSERT_TIME");
					this.OnTR1_INSERT_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR1_PLAN_FINISH_DATE", DbType="VarChar(50)")]
		public string TR1_PLAN_FINISH_DATE
		{
			get
			{
				return this._TR1_PLAN_FINISH_DATE;
			}
			set
			{
				if ((this._TR1_PLAN_FINISH_DATE != value))
				{
					this.OnTR1_PLAN_FINISH_DATEChanging(value);
					this.SendPropertyChanging();
					this._TR1_PLAN_FINISH_DATE = value;
					this.SendPropertyChanged("TR1_PLAN_FINISH_DATE");
					this.OnTR1_PLAN_FINISH_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
