#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPP_FOWAG_OSA.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB__PLANT_OSA_KPT")]
	public partial class DB__PLANT_OSADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_M_AKSE(TBL_M_AKSE instance);
    partial void UpdateTBL_M_AKSE(TBL_M_AKSE instance);
    partial void DeleteTBL_M_AKSE(TBL_M_AKSE instance);
    partial void InsertTBL_R_MENU(TBL_R_MENU instance);
    partial void UpdateTBL_R_MENU(TBL_R_MENU instance);
    partial void DeleteTBL_R_MENU(TBL_R_MENU instance);
    partial void InsertTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void UpdateTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void DeleteTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void InsertTBL_T_UPLOADPAP(TBL_T_UPLOADPAP instance);
    partial void UpdateTBL_T_UPLOADPAP(TBL_T_UPLOADPAP instance);
    partial void DeleteTBL_T_UPLOADPAP(TBL_T_UPLOADPAP instance);
    #endregion
		
		public DB__PLANT_OSADataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB__PLANT_OSA_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB__PLANT_OSADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB__PLANT_OSADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB__PLANT_OSADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB__PLANT_OSADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_M_AKSE> TBL_M_AKSEs
		{
			get
			{
				return this.GetTable<TBL_M_AKSE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_MENU> TBL_R_MENUs
		{
			get
			{
				return this.GetTable<TBL_R_MENU>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_SUB_MENU> TBL_R_SUB_MENUs
		{
			get
			{
				return this.GetTable<TBL_R_SUB_MENU>();
			}
		}
		
		public System.Data.Linq.Table<VW_R_MENU> VW_R_MENUs
		{
			get
			{
				return this.GetTable<VW_R_MENU>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_UPLOADPAP> TBL_T_UPLOADPAPs
		{
			get
			{
				return this.GetTable<TBL_T_UPLOADPAP>();
			}
		}
		
		public System.Data.Linq.Table<VW_REGISTER> VW_REGISTERs
		{
			get
			{
				return this.GetTable<VW_REGISTER>();
			}
		}
		
		public System.Data.Linq.Table<VW_REGISTER_BACKLOG> VW_REGISTER_BACKLOGs
		{
			get
			{
				return this.GetTable<VW_REGISTER_BACKLOG>();
			}
		}
		
		public System.Data.Linq.Table<VW_LABEL_FORM> VW_LABEL_FORMs
		{
			get
			{
				return this.GetTable<VW_LABEL_FORM>();
			}
		}
		
		public System.Data.Linq.Table<VW_KARYAWAN_PLANT> VW_KARYAWAN_PLANTs
		{
			get
			{
				return this.GetTable<VW_KARYAWAN_PLANT>();
			}
		}
		
		public System.Data.Linq.Table<VW_REVIEW_LABNUMBER> VW_REVIEW_LABNUMBERs
		{
			get
			{
				return this.GetTable<VW_REVIEW_LABNUMBER>();
			}
		}
		
		public System.Data.Linq.Table<VW_WORKGROUP_BACKLOG> VW_WORKGROUP_BACKLOGs
		{
			get
			{
				return this.GetTable<VW_WORKGROUP_BACKLOG>();
			}
		}
		
		public System.Data.Linq.Table<VW_OILBRANDTYPE> VW_OILBRANDTYPEs
		{
			get
			{
				return this.GetTable<VW_OILBRANDTYPE>();
			}
		}
		
		public System.Data.Linq.Table<VW_OIL> VW_OILs
		{
			get
			{
				return this.GetTable<VW_OIL>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insertBackPartBacklog_BCS")]
		public int sp_insertBackPartBacklog_BCS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BackPart_ID", DbType="VarChar(100)")] string backPart_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PartNumber", DbType="VarChar(80)")] string partNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoBackLog", DbType="VarChar(30)")] string noBackLog, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QtyPart", DbType="Int")] System.Nullable<int> qtyPart, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InspectionDate", DbType="Date")] System.Nullable<System.DateTime> inspectionDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EksInspection", DbType="VarChar(50)")] string eksInspection, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StockCode", DbType="VarChar(50)")] string stockCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FigNo", DbType="VarChar(20)")] string figNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IndexNo", DbType="VarChar(20)")] string indexNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), backPart_ID, partNumber, noBackLog, qtyPart, inspectionDate, eksInspection, stockCode, figNo, indexNo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insertPartBacklog_BCS")]
		public int sp_insertPartBacklog_BCS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PART_ID", DbType="VarChar(80)")] string pART_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIST_CODE", DbType="VarChar(40)")] string dIST_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PART_NUMBER", DbType="VarChar(40)")] string pART_NUMBER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STOCK_CODE", DbType="VarChar(40)")] string sTOCK_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PART_DESC", DbType="VarChar(MAX)")] string pART_DESC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PART_NAME", DbType="VarChar(MAX)")] string pART_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PART_UOM", DbType="VarChar(MAX)")] string pART_UOM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS_CODE", DbType="VarChar(MAX)")] string cLASS_CODE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pART_ID, dIST_CODE, pART_NUMBER, sTOCK_CODE, pART_DESC, pART_NAME, pART_UOM, cLASS_CODE);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_AKSES")]
	public partial class TBL_M_AKSE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Menu;
		
		private int _ID_Role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MenuChanging(int value);
    partial void OnID_MenuChanged();
    partial void OnID_RoleChanging(int value);
    partial void OnID_RoleChanged();
    #endregion
		
		public TBL_M_AKSE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this.OnID_RoleChanging(value);
					this.SendPropertyChanging();
					this._ID_Role = value;
					this.SendPropertyChanged("ID_Role");
					this.OnID_RoleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_MENU")]
	public partial class TBL_R_MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Menu;
		
		private string _Name_Menu;
		
		private System.Nullable<int> _Sub_Menu;
		
		private string _Icon_Menu;
		
		private string _Link_Menu;
		
		private System.Nullable<int> _Order;
		
		private string _Akses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MenuChanging(int value);
    partial void OnID_MenuChanged();
    partial void OnName_MenuChanging(string value);
    partial void OnName_MenuChanged();
    partial void OnSub_MenuChanging(System.Nullable<int> value);
    partial void OnSub_MenuChanged();
    partial void OnIcon_MenuChanging(string value);
    partial void OnIcon_MenuChanged();
    partial void OnLink_MenuChanging(string value);
    partial void OnLink_MenuChanged();
    partial void OnOrderChanging(System.Nullable<int> value);
    partial void OnOrderChanged();
    partial void OnAksesChanging(string value);
    partial void OnAksesChanged();
    #endregion
		
		public TBL_R_MENU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Menu", DbType="NVarChar(50)")]
		public string Name_Menu
		{
			get
			{
				return this._Name_Menu;
			}
			set
			{
				if ((this._Name_Menu != value))
				{
					this.OnName_MenuChanging(value);
					this.SendPropertyChanging();
					this._Name_Menu = value;
					this.SendPropertyChanged("Name_Menu");
					this.OnName_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu", DbType="Int")]
		public System.Nullable<int> Sub_Menu
		{
			get
			{
				return this._Sub_Menu;
			}
			set
			{
				if ((this._Sub_Menu != value))
				{
					this.OnSub_MenuChanging(value);
					this.SendPropertyChanging();
					this._Sub_Menu = value;
					this.SendPropertyChanged("Sub_Menu");
					this.OnSub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon_Menu", DbType="NVarChar(150)")]
		public string Icon_Menu
		{
			get
			{
				return this._Icon_Menu;
			}
			set
			{
				if ((this._Icon_Menu != value))
				{
					this.OnIcon_MenuChanging(value);
					this.SendPropertyChanging();
					this._Icon_Menu = value;
					this.SendPropertyChanged("Icon_Menu");
					this.OnIcon_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Menu", DbType="NVarChar(250)")]
		public string Link_Menu
		{
			get
			{
				return this._Link_Menu;
			}
			set
			{
				if ((this._Link_Menu != value))
				{
					this.OnLink_MenuChanging(value);
					this.SendPropertyChanging();
					this._Link_Menu = value;
					this.SendPropertyChanged("Link_Menu");
					this.OnLink_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="Int")]
		public System.Nullable<int> Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this.OnOrderChanging(value);
					this.SendPropertyChanging();
					this._Order = value;
					this.SendPropertyChanged("Order");
					this.OnOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Akses", DbType="VarChar(50)")]
		public string Akses
		{
			get
			{
				return this._Akses;
			}
			set
			{
				if ((this._Akses != value))
				{
					this.OnAksesChanging(value);
					this.SendPropertyChanging();
					this._Akses = value;
					this.SendPropertyChanged("Akses");
					this.OnAksesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_SUB_MENU")]
	public partial class TBL_R_SUB_MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Sub_Menu;
		
		private System.Nullable<int> _ID_Menu;
		
		private string _Sub_Menu_Description;
		
		private string _Link_Sub_Menu;
		
		private string _Akses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Sub_MenuChanging(int value);
    partial void OnID_Sub_MenuChanged();
    partial void OnID_MenuChanging(System.Nullable<int> value);
    partial void OnID_MenuChanged();
    partial void OnSub_Menu_DescriptionChanging(string value);
    partial void OnSub_Menu_DescriptionChanged();
    partial void OnLink_Sub_MenuChanging(string value);
    partial void OnLink_Sub_MenuChanged();
    partial void OnAksesChanging(string value);
    partial void OnAksesChanged();
    #endregion
		
		public TBL_R_SUB_MENU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Sub_Menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Sub_Menu
		{
			get
			{
				return this._ID_Sub_Menu;
			}
			set
			{
				if ((this._ID_Sub_Menu != value))
				{
					this.OnID_Sub_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Sub_Menu = value;
					this.SendPropertyChanged("ID_Sub_Menu");
					this.OnID_Sub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int")]
		public System.Nullable<int> ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu_Description", DbType="NVarChar(150)")]
		public string Sub_Menu_Description
		{
			get
			{
				return this._Sub_Menu_Description;
			}
			set
			{
				if ((this._Sub_Menu_Description != value))
				{
					this.OnSub_Menu_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Sub_Menu_Description = value;
					this.SendPropertyChanged("Sub_Menu_Description");
					this.OnSub_Menu_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Sub_Menu", DbType="NVarChar(250)")]
		public string Link_Sub_Menu
		{
			get
			{
				return this._Link_Sub_Menu;
			}
			set
			{
				if ((this._Link_Sub_Menu != value))
				{
					this.OnLink_Sub_MenuChanging(value);
					this.SendPropertyChanging();
					this._Link_Sub_Menu = value;
					this.SendPropertyChanged("Link_Sub_Menu");
					this.OnLink_Sub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Akses", DbType="VarChar(50)")]
		public string Akses
		{
			get
			{
				return this._Akses;
			}
			set
			{
				if ((this._Akses != value))
				{
					this.OnAksesChanging(value);
					this.SendPropertyChanging();
					this._Akses = value;
					this.SendPropertyChanged("Akses");
					this.OnAksesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_R_MENU")]
	public partial class VW_R_MENU
	{
		
		private int _ID;
		
		private string _RoleName;
		
		private int _ID_Menu;
		
		private string _Name_Menu;
		
		private System.Nullable<int> _Sub_Menu;
		
		private string _Icon_Menu;
		
		private string _Link_Menu;
		
		private System.Nullable<int> _Order;
		
		public VW_R_MENU()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL")]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this._ID_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Menu", DbType="NVarChar(50)")]
		public string Name_Menu
		{
			get
			{
				return this._Name_Menu;
			}
			set
			{
				if ((this._Name_Menu != value))
				{
					this._Name_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu", DbType="Int")]
		public System.Nullable<int> Sub_Menu
		{
			get
			{
				return this._Sub_Menu;
			}
			set
			{
				if ((this._Sub_Menu != value))
				{
					this._Sub_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon_Menu", DbType="NVarChar(150)")]
		public string Icon_Menu
		{
			get
			{
				return this._Icon_Menu;
			}
			set
			{
				if ((this._Icon_Menu != value))
				{
					this._Icon_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Menu", DbType="NVarChar(250)")]
		public string Link_Menu
		{
			get
			{
				return this._Link_Menu;
			}
			set
			{
				if ((this._Link_Menu != value))
				{
					this._Link_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="Int")]
		public System.Nullable<int> Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this._Order = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_UPLOADPAP")]
	public partial class TBL_T_UPLOADPAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Lab;
		
		private string _LabNumber;
		
		private string _District;
		
		private string _UnitModel;
		
		private string _UnitNumber;
		
		private string _Component;
		
		private string _UnitHM;
		
		private string _OilHM;
		
		private string _OilChanged;
		
		private string _OilBrand;
		
		private string _OilType;
		
		private System.Nullable<System.DateTime> _SamplingDate;
		
		private System.Nullable<System.DateTime> _ReceivedDate;
		
		private System.Nullable<System.DateTime> _DateReported;
		
		private string _Condition;
		
		private System.Nullable<double> _Pb;
		
		private System.Nullable<double> _Fe;
		
		private System.Nullable<double> _Al;
		
		private System.Nullable<double> _Cu;
		
		private System.Nullable<double> _Cr;
		
		private System.Nullable<double> _Sn;
		
		private System.Nullable<double> _Ni;
		
		private System.Nullable<double> _Si;
		
		private System.Nullable<double> _Na;
		
		private System.Nullable<double> _Mg;
		
		private System.Nullable<double> _Zn;
		
		private System.Nullable<double> _Mo;
		
		private System.Nullable<double> _Ca;
		
		private System.Nullable<double> _P;
		
		private System.Nullable<double> _B;
		
		private System.Nullable<double> _PQ;
		
		private System.Nullable<double> _TBN;
		
		private System.Nullable<double> _TAN;
		
		private System.Nullable<double> _Soot;
		
		private double _OXl;
		
		private System.Nullable<double> _Glycol;
		
		private System.Nullable<double> _Visc;
		
		private System.Nullable<double> _Fuel;
		
		private System.Nullable<double> _WaterContent;
		
		private string _Comment;
		
		private string _Created_By;
		
		private System.Nullable<System.DateTime> _Created_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLabChanging(string value);
    partial void OnLabChanged();
    partial void OnLabNumberChanging(string value);
    partial void OnLabNumberChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnUnitModelChanging(string value);
    partial void OnUnitModelChanged();
    partial void OnUnitNumberChanging(string value);
    partial void OnUnitNumberChanged();
    partial void OnComponentChanging(string value);
    partial void OnComponentChanged();
    partial void OnUnitHMChanging(string value);
    partial void OnUnitHMChanged();
    partial void OnOilHMChanging(string value);
    partial void OnOilHMChanged();
    partial void OnOilChangedChanging(string value);
    partial void OnOilChangedChanged();
    partial void OnOilBrandChanging(string value);
    partial void OnOilBrandChanged();
    partial void OnOilTypeChanging(string value);
    partial void OnOilTypeChanged();
    partial void OnSamplingDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSamplingDateChanged();
    partial void OnReceivedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnReceivedDateChanged();
    partial void OnDateReportedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateReportedChanged();
    partial void OnConditionChanging(string value);
    partial void OnConditionChanged();
    partial void OnPbChanging(System.Nullable<double> value);
    partial void OnPbChanged();
    partial void OnFeChanging(System.Nullable<double> value);
    partial void OnFeChanged();
    partial void OnAlChanging(System.Nullable<double> value);
    partial void OnAlChanged();
    partial void OnCuChanging(System.Nullable<double> value);
    partial void OnCuChanged();
    partial void OnCrChanging(System.Nullable<double> value);
    partial void OnCrChanged();
    partial void OnSnChanging(System.Nullable<double> value);
    partial void OnSnChanged();
    partial void OnNiChanging(System.Nullable<double> value);
    partial void OnNiChanged();
    partial void OnSiChanging(System.Nullable<double> value);
    partial void OnSiChanged();
    partial void OnNaChanging(System.Nullable<double> value);
    partial void OnNaChanged();
    partial void OnMgChanging(System.Nullable<double> value);
    partial void OnMgChanged();
    partial void OnZnChanging(System.Nullable<double> value);
    partial void OnZnChanged();
    partial void OnMoChanging(System.Nullable<double> value);
    partial void OnMoChanged();
    partial void OnCaChanging(System.Nullable<double> value);
    partial void OnCaChanged();
    partial void OnPChanging(System.Nullable<double> value);
    partial void OnPChanged();
    partial void OnBChanging(System.Nullable<double> value);
    partial void OnBChanged();
    partial void OnPQChanging(System.Nullable<double> value);
    partial void OnPQChanged();
    partial void OnTBNChanging(System.Nullable<double> value);
    partial void OnTBNChanged();
    partial void OnTANChanging(System.Nullable<double> value);
    partial void OnTANChanged();
    partial void OnSootChanging(System.Nullable<double> value);
    partial void OnSootChanged();
    partial void OnOXlChanging(double value);
    partial void OnOXlChanged();
    partial void OnGlycolChanging(System.Nullable<double> value);
    partial void OnGlycolChanged();
    partial void OnViscChanging(System.Nullable<double> value);
    partial void OnViscChanged();
    partial void OnFuelChanging(System.Nullable<double> value);
    partial void OnFuelChanged();
    partial void OnWaterContentChanging(System.Nullable<double> value);
    partial void OnWaterContentChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnCreated_ByChanging(string value);
    partial void OnCreated_ByChanged();
    partial void OnCreated_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreated_DateChanged();
    #endregion
		
		public TBL_T_UPLOADPAP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lab", DbType="VarChar(100)")]
		public string Lab
		{
			get
			{
				return this._Lab;
			}
			set
			{
				if ((this._Lab != value))
				{
					this.OnLabChanging(value);
					this.SendPropertyChanging();
					this._Lab = value;
					this.SendPropertyChanged("Lab");
					this.OnLabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LabNumber", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LabNumber
		{
			get
			{
				return this._LabNumber;
			}
			set
			{
				if ((this._LabNumber != value))
				{
					this.OnLabNumberChanging(value);
					this.SendPropertyChanging();
					this._LabNumber = value;
					this.SendPropertyChanged("LabNumber");
					this.OnLabNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="VarChar(50)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitModel", DbType="VarChar(150)")]
		public string UnitModel
		{
			get
			{
				return this._UnitModel;
			}
			set
			{
				if ((this._UnitModel != value))
				{
					this.OnUnitModelChanging(value);
					this.SendPropertyChanging();
					this._UnitModel = value;
					this.SendPropertyChanged("UnitModel");
					this.OnUnitModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="VarChar(150)")]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this.OnUnitNumberChanging(value);
					this.SendPropertyChanging();
					this._UnitNumber = value;
					this.SendPropertyChanged("UnitNumber");
					this.OnUnitNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Component", DbType="VarChar(150)")]
		public string Component
		{
			get
			{
				return this._Component;
			}
			set
			{
				if ((this._Component != value))
				{
					this.OnComponentChanging(value);
					this.SendPropertyChanging();
					this._Component = value;
					this.SendPropertyChanged("Component");
					this.OnComponentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitHM", DbType="VarChar(150)")]
		public string UnitHM
		{
			get
			{
				return this._UnitHM;
			}
			set
			{
				if ((this._UnitHM != value))
				{
					this.OnUnitHMChanging(value);
					this.SendPropertyChanging();
					this._UnitHM = value;
					this.SendPropertyChanged("UnitHM");
					this.OnUnitHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilHM", DbType="VarChar(150)")]
		public string OilHM
		{
			get
			{
				return this._OilHM;
			}
			set
			{
				if ((this._OilHM != value))
				{
					this.OnOilHMChanging(value);
					this.SendPropertyChanging();
					this._OilHM = value;
					this.SendPropertyChanged("OilHM");
					this.OnOilHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilChanged", DbType="VarChar(150)")]
		public string OilChanged
		{
			get
			{
				return this._OilChanged;
			}
			set
			{
				if ((this._OilChanged != value))
				{
					this.OnOilChangedChanging(value);
					this.SendPropertyChanging();
					this._OilChanged = value;
					this.SendPropertyChanged("OilChanged");
					this.OnOilChangedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilBrand", DbType="VarChar(150)")]
		public string OilBrand
		{
			get
			{
				return this._OilBrand;
			}
			set
			{
				if ((this._OilBrand != value))
				{
					this.OnOilBrandChanging(value);
					this.SendPropertyChanging();
					this._OilBrand = value;
					this.SendPropertyChanged("OilBrand");
					this.OnOilBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilType", DbType="VarChar(150)")]
		public string OilType
		{
			get
			{
				return this._OilType;
			}
			set
			{
				if ((this._OilType != value))
				{
					this.OnOilTypeChanging(value);
					this.SendPropertyChanging();
					this._OilType = value;
					this.SendPropertyChanged("OilType");
					this.OnOilTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SamplingDate", DbType="Date")]
		public System.Nullable<System.DateTime> SamplingDate
		{
			get
			{
				return this._SamplingDate;
			}
			set
			{
				if ((this._SamplingDate != value))
				{
					this.OnSamplingDateChanging(value);
					this.SendPropertyChanging();
					this._SamplingDate = value;
					this.SendPropertyChanged("SamplingDate");
					this.OnSamplingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceivedDate", DbType="Date")]
		public System.Nullable<System.DateTime> ReceivedDate
		{
			get
			{
				return this._ReceivedDate;
			}
			set
			{
				if ((this._ReceivedDate != value))
				{
					this.OnReceivedDateChanging(value);
					this.SendPropertyChanging();
					this._ReceivedDate = value;
					this.SendPropertyChanged("ReceivedDate");
					this.OnReceivedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReported", DbType="Date")]
		public System.Nullable<System.DateTime> DateReported
		{
			get
			{
				return this._DateReported;
			}
			set
			{
				if ((this._DateReported != value))
				{
					this.OnDateReportedChanging(value);
					this.SendPropertyChanging();
					this._DateReported = value;
					this.SendPropertyChanged("DateReported");
					this.OnDateReportedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Condition", DbType="VarChar(250)")]
		public string Condition
		{
			get
			{
				return this._Condition;
			}
			set
			{
				if ((this._Condition != value))
				{
					this.OnConditionChanging(value);
					this.SendPropertyChanging();
					this._Condition = value;
					this.SendPropertyChanged("Condition");
					this.OnConditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pb", DbType="Float")]
		public System.Nullable<double> Pb
		{
			get
			{
				return this._Pb;
			}
			set
			{
				if ((this._Pb != value))
				{
					this.OnPbChanging(value);
					this.SendPropertyChanging();
					this._Pb = value;
					this.SendPropertyChanged("Pb");
					this.OnPbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fe", DbType="Float")]
		public System.Nullable<double> Fe
		{
			get
			{
				return this._Fe;
			}
			set
			{
				if ((this._Fe != value))
				{
					this.OnFeChanging(value);
					this.SendPropertyChanging();
					this._Fe = value;
					this.SendPropertyChanged("Fe");
					this.OnFeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Al", DbType="Float")]
		public System.Nullable<double> Al
		{
			get
			{
				return this._Al;
			}
			set
			{
				if ((this._Al != value))
				{
					this.OnAlChanging(value);
					this.SendPropertyChanging();
					this._Al = value;
					this.SendPropertyChanged("Al");
					this.OnAlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cu", DbType="Float")]
		public System.Nullable<double> Cu
		{
			get
			{
				return this._Cu;
			}
			set
			{
				if ((this._Cu != value))
				{
					this.OnCuChanging(value);
					this.SendPropertyChanging();
					this._Cu = value;
					this.SendPropertyChanged("Cu");
					this.OnCuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cr", DbType="Float")]
		public System.Nullable<double> Cr
		{
			get
			{
				return this._Cr;
			}
			set
			{
				if ((this._Cr != value))
				{
					this.OnCrChanging(value);
					this.SendPropertyChanging();
					this._Cr = value;
					this.SendPropertyChanged("Cr");
					this.OnCrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sn", DbType="Float")]
		public System.Nullable<double> Sn
		{
			get
			{
				return this._Sn;
			}
			set
			{
				if ((this._Sn != value))
				{
					this.OnSnChanging(value);
					this.SendPropertyChanging();
					this._Sn = value;
					this.SendPropertyChanged("Sn");
					this.OnSnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ni", DbType="Float")]
		public System.Nullable<double> Ni
		{
			get
			{
				return this._Ni;
			}
			set
			{
				if ((this._Ni != value))
				{
					this.OnNiChanging(value);
					this.SendPropertyChanging();
					this._Ni = value;
					this.SendPropertyChanged("Ni");
					this.OnNiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Si", DbType="Float")]
		public System.Nullable<double> Si
		{
			get
			{
				return this._Si;
			}
			set
			{
				if ((this._Si != value))
				{
					this.OnSiChanging(value);
					this.SendPropertyChanging();
					this._Si = value;
					this.SendPropertyChanged("Si");
					this.OnSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Na", DbType="Float")]
		public System.Nullable<double> Na
		{
			get
			{
				return this._Na;
			}
			set
			{
				if ((this._Na != value))
				{
					this.OnNaChanging(value);
					this.SendPropertyChanging();
					this._Na = value;
					this.SendPropertyChanged("Na");
					this.OnNaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mg", DbType="Float")]
		public System.Nullable<double> Mg
		{
			get
			{
				return this._Mg;
			}
			set
			{
				if ((this._Mg != value))
				{
					this.OnMgChanging(value);
					this.SendPropertyChanging();
					this._Mg = value;
					this.SendPropertyChanged("Mg");
					this.OnMgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zn", DbType="Float")]
		public System.Nullable<double> Zn
		{
			get
			{
				return this._Zn;
			}
			set
			{
				if ((this._Zn != value))
				{
					this.OnZnChanging(value);
					this.SendPropertyChanging();
					this._Zn = value;
					this.SendPropertyChanged("Zn");
					this.OnZnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mo", DbType="Float")]
		public System.Nullable<double> Mo
		{
			get
			{
				return this._Mo;
			}
			set
			{
				if ((this._Mo != value))
				{
					this.OnMoChanging(value);
					this.SendPropertyChanging();
					this._Mo = value;
					this.SendPropertyChanged("Mo");
					this.OnMoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca", DbType="Float")]
		public System.Nullable<double> Ca
		{
			get
			{
				return this._Ca;
			}
			set
			{
				if ((this._Ca != value))
				{
					this.OnCaChanging(value);
					this.SendPropertyChanging();
					this._Ca = value;
					this.SendPropertyChanged("Ca");
					this.OnCaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P", DbType="Float")]
		public System.Nullable<double> P
		{
			get
			{
				return this._P;
			}
			set
			{
				if ((this._P != value))
				{
					this.OnPChanging(value);
					this.SendPropertyChanging();
					this._P = value;
					this.SendPropertyChanged("P");
					this.OnPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="Float")]
		public System.Nullable<double> B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this.OnBChanging(value);
					this.SendPropertyChanging();
					this._B = value;
					this.SendPropertyChanged("B");
					this.OnBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PQ", DbType="Float")]
		public System.Nullable<double> PQ
		{
			get
			{
				return this._PQ;
			}
			set
			{
				if ((this._PQ != value))
				{
					this.OnPQChanging(value);
					this.SendPropertyChanging();
					this._PQ = value;
					this.SendPropertyChanged("PQ");
					this.OnPQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBN", DbType="Float")]
		public System.Nullable<double> TBN
		{
			get
			{
				return this._TBN;
			}
			set
			{
				if ((this._TBN != value))
				{
					this.OnTBNChanging(value);
					this.SendPropertyChanging();
					this._TBN = value;
					this.SendPropertyChanged("TBN");
					this.OnTBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAN", DbType="Float")]
		public System.Nullable<double> TAN
		{
			get
			{
				return this._TAN;
			}
			set
			{
				if ((this._TAN != value))
				{
					this.OnTANChanging(value);
					this.SendPropertyChanging();
					this._TAN = value;
					this.SendPropertyChanged("TAN");
					this.OnTANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soot", DbType="Float")]
		public System.Nullable<double> Soot
		{
			get
			{
				return this._Soot;
			}
			set
			{
				if ((this._Soot != value))
				{
					this.OnSootChanging(value);
					this.SendPropertyChanging();
					this._Soot = value;
					this.SendPropertyChanged("Soot");
					this.OnSootChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OXl", DbType="Float NOT NULL")]
		public double OXl
		{
			get
			{
				return this._OXl;
			}
			set
			{
				if ((this._OXl != value))
				{
					this.OnOXlChanging(value);
					this.SendPropertyChanging();
					this._OXl = value;
					this.SendPropertyChanged("OXl");
					this.OnOXlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Glycol", DbType="Float")]
		public System.Nullable<double> Glycol
		{
			get
			{
				return this._Glycol;
			}
			set
			{
				if ((this._Glycol != value))
				{
					this.OnGlycolChanging(value);
					this.SendPropertyChanging();
					this._Glycol = value;
					this.SendPropertyChanged("Glycol");
					this.OnGlycolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visc", DbType="Float")]
		public System.Nullable<double> Visc
		{
			get
			{
				return this._Visc;
			}
			set
			{
				if ((this._Visc != value))
				{
					this.OnViscChanging(value);
					this.SendPropertyChanging();
					this._Visc = value;
					this.SendPropertyChanged("Visc");
					this.OnViscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel", DbType="Float")]
		public System.Nullable<double> Fuel
		{
			get
			{
				return this._Fuel;
			}
			set
			{
				if ((this._Fuel != value))
				{
					this.OnFuelChanging(value);
					this.SendPropertyChanging();
					this._Fuel = value;
					this.SendPropertyChanged("Fuel");
					this.OnFuelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaterContent", DbType="Float")]
		public System.Nullable<double> WaterContent
		{
			get
			{
				return this._WaterContent;
			}
			set
			{
				if ((this._WaterContent != value))
				{
					this.OnWaterContentChanging(value);
					this.SendPropertyChanging();
					this._WaterContent = value;
					this.SendPropertyChanged("WaterContent");
					this.OnWaterContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_By", DbType="VarChar(100)")]
		public string Created_By
		{
			get
			{
				return this._Created_By;
			}
			set
			{
				if ((this._Created_By != value))
				{
					this.OnCreated_ByChanging(value);
					this.SendPropertyChanging();
					this._Created_By = value;
					this.SendPropertyChanged("Created_By");
					this.OnCreated_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Created_Date
		{
			get
			{
				return this._Created_Date;
			}
			set
			{
				if ((this._Created_Date != value))
				{
					this.OnCreated_DateChanging(value);
					this.SendPropertyChanging();
					this._Created_Date = value;
					this.SendPropertyChanged("Created_Date");
					this.OnCreated_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_REGISTER")]
	public partial class VW_REGISTER
	{
		
		private string _LabNumber;
		
		private string _NoBacklog;
		
		private string _UnitNumber;
		
		private string _UnitModel;
		
		private System.Nullable<double> _UnitHM;
		
		private string _BacklogDesc;
		
		private System.Nullable<System.DateTime> _InspectonDate;
		
		private string _Inspector;
		
		private string _WorkGroup;
		
		private string _StandarJob;
		
		private string _NRPGL;
		
		private string _OriginatorID;
		
		private System.Nullable<System.DateTime> _PlanRepairDate;
		
		private System.Nullable<int> _Manpower;
		
		private System.Nullable<double> _HourEstimation;
		
		private string _Status;
		
		private string _DSTRCT;
		
		private string _ComponentCode;
		
		private string _Lab;
		
		public VW_REGISTER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LabNumber", DbType="NVarChar(100)")]
		public string LabNumber
		{
			get
			{
				return this._LabNumber;
			}
			set
			{
				if ((this._LabNumber != value))
				{
					this._LabNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoBacklog", DbType="VarChar(50)")]
		public string NoBacklog
		{
			get
			{
				return this._NoBacklog;
			}
			set
			{
				if ((this._NoBacklog != value))
				{
					this._NoBacklog = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(150)")]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this._UnitNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitModel", DbType="NVarChar(150)")]
		public string UnitModel
		{
			get
			{
				return this._UnitModel;
			}
			set
			{
				if ((this._UnitModel != value))
				{
					this._UnitModel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitHM", DbType="Float")]
		public System.Nullable<double> UnitHM
		{
			get
			{
				return this._UnitHM;
			}
			set
			{
				if ((this._UnitHM != value))
				{
					this._UnitHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BacklogDesc", DbType="VarChar(MAX)")]
		public string BacklogDesc
		{
			get
			{
				return this._BacklogDesc;
			}
			set
			{
				if ((this._BacklogDesc != value))
				{
					this._BacklogDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InspectonDate", DbType="Date")]
		public System.Nullable<System.DateTime> InspectonDate
		{
			get
			{
				return this._InspectonDate;
			}
			set
			{
				if ((this._InspectonDate != value))
				{
					this._InspectonDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inspector", DbType="VarChar(50)")]
		public string Inspector
		{
			get
			{
				return this._Inspector;
			}
			set
			{
				if ((this._Inspector != value))
				{
					this._Inspector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkGroup", DbType="VarChar(50)")]
		public string WorkGroup
		{
			get
			{
				return this._WorkGroup;
			}
			set
			{
				if ((this._WorkGroup != value))
				{
					this._WorkGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandarJob", DbType="VarChar(50)")]
		public string StandarJob
		{
			get
			{
				return this._StandarJob;
			}
			set
			{
				if ((this._StandarJob != value))
				{
					this._StandarJob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRPGL", DbType="VarChar(50)")]
		public string NRPGL
		{
			get
			{
				return this._NRPGL;
			}
			set
			{
				if ((this._NRPGL != value))
				{
					this._NRPGL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginatorID", DbType="VarChar(50)")]
		public string OriginatorID
		{
			get
			{
				return this._OriginatorID;
			}
			set
			{
				if ((this._OriginatorID != value))
				{
					this._OriginatorID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanRepairDate", DbType="Date")]
		public System.Nullable<System.DateTime> PlanRepairDate
		{
			get
			{
				return this._PlanRepairDate;
			}
			set
			{
				if ((this._PlanRepairDate != value))
				{
					this._PlanRepairDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manpower", DbType="Int")]
		public System.Nullable<int> Manpower
		{
			get
			{
				return this._Manpower;
			}
			set
			{
				if ((this._Manpower != value))
				{
					this._Manpower = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HourEstimation", DbType="Float")]
		public System.Nullable<double> HourEstimation
		{
			get
			{
				return this._HourEstimation;
			}
			set
			{
				if ((this._HourEstimation != value))
				{
					this._HourEstimation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT", DbType="VarChar(4)")]
		public string DSTRCT
		{
			get
			{
				return this._DSTRCT;
			}
			set
			{
				if ((this._DSTRCT != value))
				{
					this._DSTRCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentCode", DbType="NVarChar(150)")]
		public string ComponentCode
		{
			get
			{
				return this._ComponentCode;
			}
			set
			{
				if ((this._ComponentCode != value))
				{
					this._ComponentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lab", DbType="VarChar(100)")]
		public string Lab
		{
			get
			{
				return this._Lab;
			}
			set
			{
				if ((this._Lab != value))
				{
					this._Lab = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_REGISTER_BACKLOG")]
	public partial class VW_REGISTER_BACKLOG
	{
		
		private string _LabNumber;
		
		private string _NoBacklog;
		
		private string _UnitNumber;
		
		private string _UnitModel;
		
		private System.Nullable<double> _UnitHM;
		
		private string _BacklogDesc;
		
		private System.Nullable<System.DateTime> _InspectonDate;
		
		private string _Inspector;
		
		private string _WorkGroup;
		
		private string _StandarJob;
		
		private string _NRPGL;
		
		private string _OriginatorID;
		
		private System.Nullable<System.DateTime> _PlanRepairDate;
		
		private System.Nullable<int> _Manpower;
		
		private System.Nullable<double> _HourEstimation;
		
		private string _Status;
		
		private string _DSTRCT;
		
		private string _ComponentCode;
		
		private string _Lab;
		
		public VW_REGISTER_BACKLOG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LabNumber", DbType="NVarChar(100)")]
		public string LabNumber
		{
			get
			{
				return this._LabNumber;
			}
			set
			{
				if ((this._LabNumber != value))
				{
					this._LabNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoBacklog", DbType="VarChar(50)")]
		public string NoBacklog
		{
			get
			{
				return this._NoBacklog;
			}
			set
			{
				if ((this._NoBacklog != value))
				{
					this._NoBacklog = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="NVarChar(150)")]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this._UnitNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitModel", DbType="NVarChar(150)")]
		public string UnitModel
		{
			get
			{
				return this._UnitModel;
			}
			set
			{
				if ((this._UnitModel != value))
				{
					this._UnitModel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitHM", DbType="Float")]
		public System.Nullable<double> UnitHM
		{
			get
			{
				return this._UnitHM;
			}
			set
			{
				if ((this._UnitHM != value))
				{
					this._UnitHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BacklogDesc", DbType="VarChar(MAX)")]
		public string BacklogDesc
		{
			get
			{
				return this._BacklogDesc;
			}
			set
			{
				if ((this._BacklogDesc != value))
				{
					this._BacklogDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InspectonDate", DbType="Date")]
		public System.Nullable<System.DateTime> InspectonDate
		{
			get
			{
				return this._InspectonDate;
			}
			set
			{
				if ((this._InspectonDate != value))
				{
					this._InspectonDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inspector", DbType="VarChar(50)")]
		public string Inspector
		{
			get
			{
				return this._Inspector;
			}
			set
			{
				if ((this._Inspector != value))
				{
					this._Inspector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkGroup", DbType="VarChar(50)")]
		public string WorkGroup
		{
			get
			{
				return this._WorkGroup;
			}
			set
			{
				if ((this._WorkGroup != value))
				{
					this._WorkGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandarJob", DbType="VarChar(50)")]
		public string StandarJob
		{
			get
			{
				return this._StandarJob;
			}
			set
			{
				if ((this._StandarJob != value))
				{
					this._StandarJob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRPGL", DbType="VarChar(50)")]
		public string NRPGL
		{
			get
			{
				return this._NRPGL;
			}
			set
			{
				if ((this._NRPGL != value))
				{
					this._NRPGL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginatorID", DbType="VarChar(50)")]
		public string OriginatorID
		{
			get
			{
				return this._OriginatorID;
			}
			set
			{
				if ((this._OriginatorID != value))
				{
					this._OriginatorID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanRepairDate", DbType="Date")]
		public System.Nullable<System.DateTime> PlanRepairDate
		{
			get
			{
				return this._PlanRepairDate;
			}
			set
			{
				if ((this._PlanRepairDate != value))
				{
					this._PlanRepairDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manpower", DbType="Int")]
		public System.Nullable<int> Manpower
		{
			get
			{
				return this._Manpower;
			}
			set
			{
				if ((this._Manpower != value))
				{
					this._Manpower = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HourEstimation", DbType="Float")]
		public System.Nullable<double> HourEstimation
		{
			get
			{
				return this._HourEstimation;
			}
			set
			{
				if ((this._HourEstimation != value))
				{
					this._HourEstimation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT", DbType="VarChar(4)")]
		public string DSTRCT
		{
			get
			{
				return this._DSTRCT;
			}
			set
			{
				if ((this._DSTRCT != value))
				{
					this._DSTRCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentCode", DbType="NVarChar(150)")]
		public string ComponentCode
		{
			get
			{
				return this._ComponentCode;
			}
			set
			{
				if ((this._ComponentCode != value))
				{
					this._ComponentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lab", DbType="VarChar(100)")]
		public string Lab
		{
			get
			{
				return this._Lab;
			}
			set
			{
				if ((this._Lab != value))
				{
					this._Lab = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_LABEL_FORM")]
	public partial class VW_LABEL_FORM
	{
		
		private string _LabNumber;
		
		private string _WO;
		
		private string _DSTRCT;
		
		private string _UnitModel;
		
		private string _UnitNumber;
		
		private string _WORK_GROUP;
		
		private string _UnitHM;
		
		private string _Manufacture;
		
		private string _ComponentCode;
		
		private System.Nullable<System.DateTime> _SamplingDate;
		
		private string _OilBrand;
		
		private string _OilType;
		
		private string _OilSpec;
		
		private System.Nullable<int> _OilHM;
		
		private string _NRP;
		
		private string _PIC;
		
		private System.Nullable<int> _OilChanged;
		
		private string _Status;
		
		private string _TypeOilHM;
		
		private string _Component;
		
		public VW_LABEL_FORM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LabNumber", DbType="VarChar(50)")]
		public string LabNumber
		{
			get
			{
				return this._LabNumber;
			}
			set
			{
				if ((this._LabNumber != value))
				{
					this._LabNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO", DbType="Char(8)")]
		public string WO
		{
			get
			{
				return this._WO;
			}
			set
			{
				if ((this._WO != value))
				{
					this._WO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT", DbType="Char(4)")]
		public string DSTRCT
		{
			get
			{
				return this._DSTRCT;
			}
			set
			{
				if ((this._DSTRCT != value))
				{
					this._DSTRCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitModel", DbType="Char(12)")]
		public string UnitModel
		{
			get
			{
				return this._UnitModel;
			}
			set
			{
				if ((this._UnitModel != value))
				{
					this._UnitModel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="Char(12)")]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this._UnitNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_GROUP", DbType="Char(7)")]
		public string WORK_GROUP
		{
			get
			{
				return this._WORK_GROUP;
			}
			set
			{
				if ((this._WORK_GROUP != value))
				{
					this._WORK_GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitHM", DbType="VarChar(50)")]
		public string UnitHM
		{
			get
			{
				return this._UnitHM;
			}
			set
			{
				if ((this._UnitHM != value))
				{
					this._UnitHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manufacture", DbType="Char(8)")]
		public string Manufacture
		{
			get
			{
				return this._Manufacture;
			}
			set
			{
				if ((this._Manufacture != value))
				{
					this._Manufacture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentCode", DbType="Char(4)")]
		public string ComponentCode
		{
			get
			{
				return this._ComponentCode;
			}
			set
			{
				if ((this._ComponentCode != value))
				{
					this._ComponentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SamplingDate", DbType="Date")]
		public System.Nullable<System.DateTime> SamplingDate
		{
			get
			{
				return this._SamplingDate;
			}
			set
			{
				if ((this._SamplingDate != value))
				{
					this._SamplingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilBrand", DbType="VarChar(50)")]
		public string OilBrand
		{
			get
			{
				return this._OilBrand;
			}
			set
			{
				if ((this._OilBrand != value))
				{
					this._OilBrand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilType", DbType="VarChar(50)")]
		public string OilType
		{
			get
			{
				return this._OilType;
			}
			set
			{
				if ((this._OilType != value))
				{
					this._OilType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilSpec", DbType="VarChar(50)")]
		public string OilSpec
		{
			get
			{
				return this._OilSpec;
			}
			set
			{
				if ((this._OilSpec != value))
				{
					this._OilSpec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilHM", DbType="Int")]
		public System.Nullable<int> OilHM
		{
			get
			{
				return this._OilHM;
			}
			set
			{
				if ((this._OilHM != value))
				{
					this._OilHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC", DbType="VarChar(50)")]
		public string PIC
		{
			get
			{
				return this._PIC;
			}
			set
			{
				if ((this._PIC != value))
				{
					this._PIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilChanged", DbType="Int")]
		public System.Nullable<int> OilChanged
		{
			get
			{
				return this._OilChanged;
			}
			set
			{
				if ((this._OilChanged != value))
				{
					this._OilChanged = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOilHM", DbType="VarChar(50)")]
		public string TypeOilHM
		{
			get
			{
				return this._TypeOilHM;
			}
			set
			{
				if ((this._TypeOilHM != value))
				{
					this._TypeOilHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Component", DbType="VarChar(50)")]
		public string Component
		{
			get
			{
				return this._Component;
			}
			set
			{
				if ((this._Component != value))
				{
					this._Component = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KARYAWAN_PLANT")]
	public partial class VW_KARYAWAN_PLANT
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NAME;
		
		public VW_KARYAWAN_PLANT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_REVIEW_LABNUMBER")]
	public partial class VW_REVIEW_LABNUMBER
	{
		
		private string _LabNumber;
		
		private string _NoWO;
		
		private string _UnitHM;
		
		private string _Component;
		
		private System.Nullable<System.DateTime> _SamplingDate;
		
		private string _OilBrand;
		
		private string _OilType;
		
		private string _OilSpec;
		
		private System.Nullable<int> _OilHM;
		
		private string _NRP;
		
		private string _PIC;
		
		private System.Nullable<int> _OilChanged;
		
		private string _District;
		
		private string _TypeOilHM;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedDate;
		
		private string _UpdateBy;
		
		private string _Status;
		
		private string _SampleType;
		
		private string _Manufacture;
		
		private string _UnitModel;
		
		private string _UnitNumber;
		
		private string _ComponentCode;
		
		public VW_REVIEW_LABNUMBER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LabNumber", DbType="VarChar(50)")]
		public string LabNumber
		{
			get
			{
				return this._LabNumber;
			}
			set
			{
				if ((this._LabNumber != value))
				{
					this._LabNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoWO", DbType="VarChar(50)")]
		public string NoWO
		{
			get
			{
				return this._NoWO;
			}
			set
			{
				if ((this._NoWO != value))
				{
					this._NoWO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitHM", DbType="VarChar(50)")]
		public string UnitHM
		{
			get
			{
				return this._UnitHM;
			}
			set
			{
				if ((this._UnitHM != value))
				{
					this._UnitHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Component", DbType="VarChar(200)")]
		public string Component
		{
			get
			{
				return this._Component;
			}
			set
			{
				if ((this._Component != value))
				{
					this._Component = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SamplingDate", DbType="Date")]
		public System.Nullable<System.DateTime> SamplingDate
		{
			get
			{
				return this._SamplingDate;
			}
			set
			{
				if ((this._SamplingDate != value))
				{
					this._SamplingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilBrand", DbType="VarChar(50)")]
		public string OilBrand
		{
			get
			{
				return this._OilBrand;
			}
			set
			{
				if ((this._OilBrand != value))
				{
					this._OilBrand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilType", DbType="VarChar(50)")]
		public string OilType
		{
			get
			{
				return this._OilType;
			}
			set
			{
				if ((this._OilType != value))
				{
					this._OilType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilSpec", DbType="VarChar(50)")]
		public string OilSpec
		{
			get
			{
				return this._OilSpec;
			}
			set
			{
				if ((this._OilSpec != value))
				{
					this._OilSpec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilHM", DbType="Int")]
		public System.Nullable<int> OilHM
		{
			get
			{
				return this._OilHM;
			}
			set
			{
				if ((this._OilHM != value))
				{
					this._OilHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC", DbType="VarChar(50)")]
		public string PIC
		{
			get
			{
				return this._PIC;
			}
			set
			{
				if ((this._PIC != value))
				{
					this._PIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilChanged", DbType="Int")]
		public System.Nullable<int> OilChanged
		{
			get
			{
				return this._OilChanged;
			}
			set
			{
				if ((this._OilChanged != value))
				{
					this._OilChanged = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="VarChar(50)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this._District = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOilHM", DbType="VarChar(50)")]
		public string TypeOilHM
		{
			get
			{
				return this._TypeOilHM;
			}
			set
			{
				if ((this._TypeOilHM != value))
				{
					this._TypeOilHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="Date")]
		public System.Nullable<System.DateTime> UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this._UpdatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="VarChar(50)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this._UpdateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleType", DbType="VarChar(50)")]
		public string SampleType
		{
			get
			{
				return this._SampleType;
			}
			set
			{
				if ((this._SampleType != value))
				{
					this._SampleType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manufacture", DbType="Char(8)")]
		public string Manufacture
		{
			get
			{
				return this._Manufacture;
			}
			set
			{
				if ((this._Manufacture != value))
				{
					this._Manufacture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitModel", DbType="Char(12)")]
		public string UnitModel
		{
			get
			{
				return this._UnitModel;
			}
			set
			{
				if ((this._UnitModel != value))
				{
					this._UnitModel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitNumber", DbType="Char(12)")]
		public string UnitNumber
		{
			get
			{
				return this._UnitNumber;
			}
			set
			{
				if ((this._UnitNumber != value))
				{
					this._UnitNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentCode", DbType="Char(4)")]
		public string ComponentCode
		{
			get
			{
				return this._ComponentCode;
			}
			set
			{
				if ((this._ComponentCode != value))
				{
					this._ComponentCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_WORKGROUP_BACKLOG")]
	public partial class VW_WORKGROUP_BACKLOG
	{
		
		private string _work_group;
		
		private string _work_grp_desc;
		
		private string _dstrct_code;
		
		public VW_WORKGROUP_BACKLOG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_work_group", DbType="VarChar(7)")]
		public string work_group
		{
			get
			{
				return this._work_group;
			}
			set
			{
				if ((this._work_group != value))
				{
					this._work_group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_work_grp_desc", DbType="VarChar(40)")]
		public string work_grp_desc
		{
			get
			{
				return this._work_grp_desc;
			}
			set
			{
				if ((this._work_grp_desc != value))
				{
					this._work_grp_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dstrct_code", DbType="VarChar(4)")]
		public string dstrct_code
		{
			get
			{
				return this._dstrct_code;
			}
			set
			{
				if ((this._dstrct_code != value))
				{
					this._dstrct_code = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_OILBRANDTYPE")]
	public partial class VW_OILBRANDTYPE
	{
		
		private string _OilBrand;
		
		private int _Id_Brand;
		
		private int _Id_Type;
		
		private string _OilType;
		
		public VW_OILBRANDTYPE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilBrand", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string OilBrand
		{
			get
			{
				return this._OilBrand;
			}
			set
			{
				if ((this._OilBrand != value))
				{
					this._OilBrand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Brand", DbType="Int NOT NULL")]
		public int Id_Brand
		{
			get
			{
				return this._Id_Brand;
			}
			set
			{
				if ((this._Id_Brand != value))
				{
					this._Id_Brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Type", DbType="Int NOT NULL")]
		public int Id_Type
		{
			get
			{
				return this._Id_Type;
			}
			set
			{
				if ((this._Id_Type != value))
				{
					this._Id_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilType", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string OilType
		{
			get
			{
				return this._OilType;
			}
			set
			{
				if ((this._OilType != value))
				{
					this._OilType = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_OIL")]
	public partial class VW_OIL
	{
		
		private int _Id_Spec;
		
		private string _OilSpec;
		
		private int _Id_Brand;
		
		private string _OilBrand;
		
		private int _Id_Type;
		
		private string _OilType;
		
		public VW_OIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Spec", DbType="Int NOT NULL")]
		public int Id_Spec
		{
			get
			{
				return this._Id_Spec;
			}
			set
			{
				if ((this._Id_Spec != value))
				{
					this._Id_Spec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilSpec", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string OilSpec
		{
			get
			{
				return this._OilSpec;
			}
			set
			{
				if ((this._OilSpec != value))
				{
					this._OilSpec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Brand", DbType="Int NOT NULL")]
		public int Id_Brand
		{
			get
			{
				return this._Id_Brand;
			}
			set
			{
				if ((this._Id_Brand != value))
				{
					this._Id_Brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilBrand", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string OilBrand
		{
			get
			{
				return this._OilBrand;
			}
			set
			{
				if ((this._OilBrand != value))
				{
					this._OilBrand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Type", DbType="Int NOT NULL")]
		public int Id_Type
		{
			get
			{
				return this._Id_Type;
			}
			set
			{
				if ((this._Id_Type != value))
				{
					this._Id_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilType", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string OilType
		{
			get
			{
				return this._OilType;
			}
			set
			{
				if ((this._OilType != value))
				{
					this._OilType = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
